import type { Exercise, Level, SkillId } from './schema';

type QuestionInput = Omit<Exercise, 'id' | 'skill' | 'hint' | 'explanation'> &
  Partial<Pick<Exercise, 'id' | 'hint' | 'explanation'>>;
type ExamInput = [title: string, prompt: string, solutionSql: string, explanation?: string];

interface AdvancedInput {
  number: number;
  id: string;
  title: string;
  subtitle: string;
  skill: SkillId;
  rules: Level['rules'];
  practice: QuestionInput[];
  exam: ExamInput[];
}

function makeLevel(input: AdvancedInput): Level {
  if (input.practice.length < 7 || input.exam.length !== 8) {
    throw new Error(`${input.id}: advanced levels need seven practices and eight exam variants`);
  }
  const exercises = input.practice.map((item, index): Exercise => ({
    ...item,
    id: item.id ?? `l${input.number}-p${index + 1}`,
    skill: input.skill,
    hint: item.hint ?? 'Inspect the relevant rows and build the query one part at a time.',
    explanation: item.explanation ?? 'The reference query returns the requested result.',
    difficulty: item.difficulty ?? (index === input.practice.length - 1 ? 'boss'
      : index === 0 ? 'warmup' : index >= 5 ? 'stretch' : 'core'),
  }));
  const exam = input.exam.map(([title, prompt, solutionSql, explanation], index): Exercise => ({
    id: `l${input.number}-e${index + 1}`,
    skill: input.skill,
    kind: index < 4 ? 'write' : index < 6 ? 'match' : 'answer',
    title,
    prompt,
    solutionSql,
    hint: 'Use the table schema and the rules from this level.',
    explanation: explanation ?? 'Compare your reasoning with the reference query.',
    difficulty: index >= 6 ? 'stretch' : 'core',
  }));
  return {
    id: input.id,
    number: input.number,
    title: input.title,
    subtitle: input.subtitle,
    skills: [input.skill],
    rules: input.rules,
    exercises,
    exam,
    examDrawCount: 4,
    passCount: 3,
  };
}

export const ADVANCED_LEVELS: Level[] = [
  makeLevel({
    number: 5,
    id: 'distinct',
    title: 'Find the useful few',
    subtitle: 'Remove duplicates and turn prices into useful numbers.',
    skill: 'distinct',
    rules: [
      { title: 'Keep unique values', body: 'DISTINCT removes repeated result rows. COUNT(DISTINCT column) counts each value once.',
        example: 'SELECT DISTINCT city FROM customers;' },
      { title: 'Calculate as you read', body: 'Expressions can turn stored values into new columns. Give each calculation a clear name with AS.',
        example: 'SELECT quantity * 2 AS double_quantity FROM order_items;' },
      { title: 'Choose the right size', body: 'LIMIT keeps the first few sorted rows. ROUND controls decimal places. A cast changes a value’s type: x::numeric or CAST(x AS numeric). Dividing two integers drops the fraction (7 / 2 is 3), so cast one side or use a decimal such as 7.0.',
        example: 'SELECT name, ROUND(price * 0.9, 2) FROM products ORDER BY price DESC LIMIT 3;\nSELECT quantity / 2 AS whole, quantity::numeric / 2 AS exact FROM order_items;' },
    ],
    practice: [
      { kind: 'write', title: 'Customer cities',
        prompt: 'Marketing needs one entry for each city where a customer lives.',
        hint: 'Remove repeated city values.',
        solutionSql: 'SELECT DISTINCT city FROM customers;' },
      { kind: 'complete', title: 'Sale prices',
        prompt: 'Price every product at ten percent off, with two decimal places.',
        solutionSql: 'SELECT name, ROUND(price * 0.9, 2) AS sale_price FROM products;',
        templateParts: ['SELECT name, ', '(price * 0.9, 2) AS sale_price FROM products;'],
        blankLabels: ['rounding function'], blankAnswers: ['ROUND'],
        hint: 'Use the function that rounds a number.' },
      { kind: 'predict', title: 'A division check',
        prompt: 'What value does this calculation return?',
        starterSql: 'SELECT 7::numeric / 2;',
        solutionSql: 'SELECT 7::numeric / 2;',
        answerOptions: [
          { id: 'a', label: '3', value: '3' },
          { id: 'b', label: '3.5', value: '3.5' },
          { id: 'c', label: '4', value: '4' },
          { id: 'd', label: '7', value: '7' },
        ], correctAnswerId: 'b', hint: 'A numeric cast preserves the fractional part.' },
      { kind: 'answer', title: 'Reach of the shop',
        prompt: 'How many different cities have at least one customer?',
        solutionSql: 'SELECT COUNT(DISTINCT city) FROM customers;',
        hint: 'Count the unique city values.' },
      { kind: 'match', title: '{limit} costliest products',
        prompt: 'Produce the target table of the {limit} most expensive products.',
        solutionSql: 'SELECT name, price FROM products ORDER BY price DESC, name ASC LIMIT {limit};',
        orderMatters: true, hint: 'Put the largest price first, then keep {limit} rows.',
        params: { limit: { pick: [2, 3, 4] } } },
      { kind: 'bug', title: 'Missing category',
        prompt: 'The merchandise report leaves out a category. Correct the running query.',
        starterSql: 'SELECT DISTINCT category FROM products WHERE price > 20;',
        solutionSql: 'SELECT DISTINCT category FROM products;',
        hint: 'The report needs every category, even if its products are inexpensive.' },
      { id: 'l5-p8', kind: 'bug', title: 'A rounded-down ratio',
        prompt: 'Finance expected a fractional ratio, but this calculation rounds down. Repair it.',
        starterSql: 'SELECT 7 / 2 AS ratio;',
        solutionSql: 'SELECT 7::numeric / 2 AS ratio;',
        commonMistakes: [{ sql: 'SELECT 7 / 2 AS ratio;',
          feedback: 'Two integers divide to an integer here. Cast one side to numeric.' }] },
      { kind: 'write', title: 'Category price brief', difficulty: 'boss',
        id: 'l5-p7',
        prompt: 'For each category, show its average product price rounded to two decimals. Put the least costly average first.',
        solutionSql: 'SELECT category, ROUND(AVG(price), 2) AS avg_price FROM products GROUP BY category ORDER BY avg_price ASC, category ASC;',
        orderMatters: true,
        hint: 'Combine grouping with an average, rounding, and a final sort.' },
    ],
    exam: [
      ['Order states', 'List each order state once.', 'SELECT DISTINCT status FROM orders;'],
      ['New prices', 'Give each product a price after a ten percent increase, rounded to cents.',
        'SELECT name, ROUND(price * 1.1, 2) AS new_price FROM products;'],
      ['Five costliest', 'List the five costliest products with their prices.',
        'SELECT name, price FROM products ORDER BY price DESC, name LIMIT 5;'],
      ['Doubled units', 'Show each line item ID and twice its quantity.',
        'SELECT id, quantity * 2 AS doubled_quantity FROM order_items;'],
      ['Category labels', 'Match the table of unique category labels.',
        'SELECT DISTINCT category FROM products ORDER BY category;'],
      ['Inexpensive picks', 'Match the table of three inexpensive products.',
        'SELECT name, price FROM products WHERE price < 10 ORDER BY price, name LIMIT 3;'],
      ['How many categories?', 'Enter the number of distinct product categories.',
        'SELECT COUNT(DISTINCT category) FROM products;'],
      ['Average ticket price', 'Enter the average product price rounded to cents.',
        'SELECT ROUND(AVG(price), 2) FROM products;'],
    ],
  }),
  makeLevel({
    number: 6, id: 'conditions', title: 'Ask sharper questions',
    subtitle: 'Combine ranges, patterns, and conditions without surprises.', skill: 'conditions',
    rules: [
      { title: 'Choose from a set', body: 'IN tests membership in a list; BETWEEN includes both endpoints.',
        example: "SELECT id FROM orders WHERE status IN ('pending', 'shipped');\nSELECT id FROM orders WHERE order_date BETWEEN '2026-02-01' AND '2026-02-28';" },
      { title: 'Find text patterns', body: 'LIKE matches a pattern, and % stands for any run of characters. ILIKE does the same without caring about letter case.',
        example: "SELECT name FROM products WHERE name ILIKE 'p%';" },
      { title: 'Group your logic', body: 'AND is evaluated before OR. NOT reverses a condition. Parentheses show exactly which conditions belong together.',
        example: "WHERE (status = 'pending' OR status = 'shipped') AND order_date >= '2026-01-10'" },
    ],
    practice: [
      { kind: 'write', title: 'January fulfillment list',
        prompt: 'Operations needs January 2026 orders that are either shipped or pending.',
        solutionSql: "SELECT id, status FROM orders WHERE status IN ('shipped', 'pending') AND order_date BETWEEN '2026-01-01' AND '2026-01-31';",
        hint: 'Use one membership test and an inclusive date range.' },
      { kind: 'complete', title: 'Names beginning with P',
        prompt: 'Find product names beginning with P, regardless of capitalization.',
        solutionSql: "SELECT name FROM products WHERE name ILIKE 'P%';",
        templateParts: ['SELECT name FROM products WHERE name ', " 'P%';"],
        blankLabels: ['case-insensitive pattern operator'], blankAnswers: ['ILIKE'] },
      { kind: 'predict', title: 'Which condition wins?',
        prompt: 'What number does this logical expression return?',
        starterSql: 'SELECT (TRUE OR FALSE AND FALSE)::int;',
        solutionSql: 'SELECT (TRUE OR FALSE AND FALSE)::int;',
        answerOptions: [
          { id: 'a', label: '0', value: '0' }, { id: 'b', label: '1', value: '1' },
          { id: 'c', label: '2', value: '2' }, { id: 'd', label: 'NULL', value: 'NULL' },
        ], correctAnswerId: 'b', hint: 'AND is evaluated before OR.' },
      { kind: 'answer', title: 'Names containing o',
        prompt: 'How many product names contain the letter o in either case?',
        solutionSql: "SELECT COUNT(*) FROM products WHERE name ILIKE '%o%';" },
      { kind: 'match', title: 'Orders needing action',
        prompt: 'Recreate the target list of pending or cancelled orders from 2026.',
        solutionSql: "SELECT id, status FROM orders WHERE status IN ('pending', 'cancelled') AND order_date >= '2026-01-01' ORDER BY id DESC;",
        orderMatters: true },
      { kind: 'bug', title: 'Old orders slipped in',
        prompt: 'The report includes older shipped orders. Fix the condition grouping.',
        starterSql: "SELECT id FROM orders WHERE status = 'shipped' OR status = 'pending' AND order_date >= '2026-01-10';",
        solutionSql: "SELECT id FROM orders WHERE (status = 'shipped' OR status = 'pending') AND order_date >= '2026-01-10';",
        hint: 'The date rule must apply to both statuses.',
        commonMistakes: [{
          sql: "SELECT id FROM orders WHERE status = 'shipped' OR status = 'pending' AND order_date >= '2026-01-10';",
          feedback: 'AND is evaluated before OR. Put the two status choices in parentheses.',
        }] },
      { kind: 'order', title: 'Condition ordering sequence',
        prompt: 'Arrange the clauses in the correct order to list order IDs and dates for pending orders placed in 2026, sorted latest first.',
        hint: 'Syntactic sequence: SELECT -> FROM -> WHERE -> ORDER BY.',
        explanation: 'SQL structure requires the SELECT list, FROM table, WHERE conditions with parentheses, then ORDER BY.',
        clauses: [
          'SELECT id, order_date',
          'FROM orders',
          "WHERE status = 'pending' AND order_date >= '2026-01-01'",
          'ORDER BY order_date DESC, id DESC;',
        ],
        solutionSql: "SELECT id, order_date\nFROM orders\nWHERE status = 'pending' AND order_date >= '2026-01-01'\nORDER BY order_date DESC, id DESC;",
        orderMatters: true },
      { kind: 'write', title: 'Repeat recent buyers', difficulty: 'boss',
        prompt: 'Find customers with at least two shipped orders dated January 2026 or later. Show their ID, name, and count.',
        solutionSql: "SELECT c.id, c.name, COUNT(o.id) AS shipped_count FROM customers c JOIN orders o ON o.customer_id = c.id WHERE o.status = 'shipped' AND o.order_date >= '2026-01-01' GROUP BY c.id, c.name HAVING COUNT(o.id) >= 2;",
        hint: 'Filter the qualifying orders, then count them per customer.' },
    ],
    exam: [
      ['Midrange stock', 'List names and prices of products costing from 10 through 30.',
        'SELECT name, price FROM products WHERE price BETWEEN 10 AND 30;'],
      ['Customers beginning with A', 'List names of customers whose names start with A in either case.',
        "SELECT name FROM customers WHERE name ILIKE 'a%';"],
      ['Active recent orders', 'Show IDs of orders since January 2026 that were not cancelled.',
        "SELECT id FROM orders WHERE order_date >= '2026-01-01' AND NOT status = 'cancelled';"],
      ['Affordable home or gear', 'Show products in Home or Gear costing less than 30.',
        "SELECT name, category FROM products WHERE category IN ('Home', 'Gear') AND price < 30;"],
      ['Five open order rows', 'Recreate the target table of five non-cancelled orders.',
        "SELECT id, status FROM orders WHERE status <> 'cancelled' ORDER BY id LIMIT 5;"],
      ['Names with e', 'Recreate the target table of five product names containing e.',
        "SELECT name FROM products WHERE name ILIKE '%e%' ORDER BY name LIMIT 5;"],
      ['Pending this January', 'How many pending orders were placed in January 2026?',
        "SELECT COUNT(*) FROM orders WHERE status = 'pending' AND order_date BETWEEN '2026-01-01' AND '2026-01-31';"],
      ['Midrange count', 'How many products cost from 10 through 30?',
        'SELECT COUNT(*) FROM products WHERE price BETWEEN 10 AND 30;'],
    ],
  }),
  makeLevel({
    number: 7, id: 'nulls', title: 'Mind the missing values',
    subtitle: 'Read gaps in the data without losing records.', skill: 'nulls',
    rules: [
      { title: 'NULL means unknown', body: 'Use IS NULL or IS NOT NULL. Ordinary equality does not find missing values.',
        example: 'SELECT id FROM customers WHERE email IS NULL;' },
      { title: 'Give gaps a label', body: 'COALESCE returns the first available value. NULLIF(a, b) turns a into NULL when it equals b.',
        example: "SELECT COALESCE(discount_code, 'none'), NULLIF(status, 'cancelled') FROM orders;" },
      { title: 'Count carefully', body: 'COUNT(*) counts rows; COUNT(column) skips NULLs. This matters most after joins.',
        example: 'SELECT COUNT(*) AS all_rows, COUNT(rating) AS rated FROM reviews;' },
      { title: 'Keep rows with no match', body: 'LEFT JOIN keeps every row from the left table, even when nothing matches on the right. Those right-side columns are NULL, so COUNT(column) counts zero for them and IS NULL finds them. Level 9 goes deeper.',
        example: 'SELECT p.name, COUNT(r.id) AS review_count FROM products p LEFT JOIN reviews r ON r.product_id = p.id GROUP BY p.id, p.name;' },
    ],
    practice: [
      { kind: 'write', title: 'Missing contact details',
        prompt: 'Find customers without an email address. Show their ID and name.',
        solutionSql: 'SELECT id, name FROM customers WHERE email IS NULL;' },
      { kind: 'complete', title: 'Discount labels',
        prompt: 'Give each order a readable discount label, including orders with no code.',
        solutionSql: "SELECT id, COALESCE(discount_code, 'none') AS discount_label FROM orders;",
        templateParts: ['SELECT id, ', "(discount_code, 'none') AS discount_label FROM orders;"],
        blankLabels: ['fallback function'], blankAnswers: ['COALESCE'] },
      { kind: 'predict', title: 'Rated review count',
        prompt: 'How many ratings does this query count?',
        starterSql: 'SELECT COUNT(rating) FROM reviews WHERE id <= 3;',
        solutionSql: 'SELECT COUNT(rating) FROM reviews WHERE id <= 3;',
        answerOptions: [
          { id: 'a', label: '1', value: '1' }, { id: 'b', label: '2', value: '2' },
          { id: 'c', label: '3', value: '3' }, { id: 'd', label: '4', value: '4' },
        ], correctAnswerId: 'b', hint: 'One review has no rating.' },
      { kind: 'answer', title: 'Unreferred customers',
        prompt: 'How many customers have no referrer recorded?',
        solutionSql: 'SELECT COUNT(*) FROM customers WHERE referred_by IS NULL;' },
      { kind: 'match', title: 'Unknown email labels',
        prompt: 'Recreate the target list of customers with missing email addresses.',
        solutionSql: "SELECT name, COALESCE(email, 'missing') AS email FROM customers WHERE email IS NULL ORDER BY id;" },
      { kind: 'bug', title: 'The empty contact report',
        prompt: 'The report runs but finds nobody. Repair its missing-value test.',
        starterSql: 'SELECT id, name FROM customers WHERE email = NULL;',
        solutionSql: 'SELECT id, name FROM customers WHERE email IS NULL;',
        commonMistakes: [{ sql: 'SELECT id, name FROM customers WHERE email = NULL;',
          feedback: 'Equality cannot match NULL. Use IS NULL.' }] },
      { kind: 'write', title: 'Unknown contacts and orders', difficulty: 'boss',
        prompt: 'For every customer without an email, show the customer ID, name, and number of orders, including zero.',
        solutionSql: 'SELECT c.id, c.name, COUNT(o.id) AS order_count FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE c.email IS NULL GROUP BY c.id, c.name;',
        hint: 'Keep unmatched customers, then count order IDs rather than rows.' },
    ],
    exam: [
      ['Unrated products', 'Show product IDs with a review that has no rating.',
        'SELECT product_id FROM reviews WHERE rating IS NULL;'],
      ['Not yet shipped', 'Show IDs of orders without a shipment timestamp.',
        'SELECT id FROM orders WHERE shipped_at IS NULL;'],
      ['No referrer', 'Show IDs and names of customers without a recorded referrer.',
        'SELECT id, name FROM customers WHERE referred_by IS NULL;'],
      ['Other discount codes', 'Show each order ID and its discount code, except treat WELCOME10 as missing.',
        "SELECT id, NULLIF(discount_code, 'WELCOME10') AS other_code FROM orders;"],
      ['Customers with no orders', 'Recreate the target table of customers who have never ordered.',
        'SELECT c.id, c.name FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.id IS NULL;'],
      ['Readable discounts', 'Recreate the target labels for the first five order IDs.',
        "SELECT id, COALESCE(discount_code, 'none') AS discount_label FROM orders WHERE id <= 5 ORDER BY id;"],
      ['Unrated count', 'How many reviews lack a rating?',
        'SELECT COUNT(*) FROM reviews WHERE rating IS NULL;'],
      ['Discount use', 'How many orders have a discount code?',
        'SELECT COUNT(discount_code) FROM orders;'],
    ],
  }),
  makeLevel({
    number: 8, id: 'case', title: 'Turn rows into decisions',
    subtitle: 'Classify values and count only the events that matter.', skill: 'case',
    rules: [
      { title: 'Classify each row', body: 'CASE turns conditions into a label or number for each row.',
        example: "SELECT CASE WHEN price >= 20 THEN 'premium' ELSE 'standard' END FROM products;" },
      { title: 'Count a subset', body: 'FILTER limits an aggregate to matching rows without dropping the other groups.',
        example: "SELECT COUNT(*) FILTER (WHERE status = 'shipped') FROM orders;" },
      { title: 'Summarize several conditions', body: 'Put several filtered aggregates in one query for a compact, pivot-like report. SUM(CASE WHEN condition THEN 1 ELSE 0 END) counts matching rows the same way.',
        example: "SELECT COUNT(*) FILTER (WHERE status = 'pending') AS pending,\n       SUM(CASE WHEN status = 'cancelled' THEN 1 ELSE 0 END) AS cancelled\nFROM orders;" },
    ],
    practice: [
      { kind: 'write', title: 'Price bands',
        prompt: 'Label products costing at least 20 as premium and the rest as standard.',
        solutionSql: "SELECT id, CASE WHEN price >= 20 THEN 'premium' ELSE 'standard' END AS price_band FROM products;" },
      { kind: 'complete', title: 'Shipped share',
        prompt: 'Complete the single number that counts shipped orders.',
        solutionSql: "SELECT COUNT(*) FILTER (WHERE status = 'shipped') AS shipped_count FROM orders;",
        templateParts: ['SELECT COUNT(*) ', ' AS shipped_count FROM orders;'],
        blankLabels: ['aggregate filter'], blankAnswers: ["FILTER (WHERE status = 'shipped')"] },
      { kind: 'predict', title: 'Whole-number division',
        prompt: 'Which word does this calculation return?',
        starterSql: "SELECT CASE WHEN 7 / 2 = 3 THEN 'integer' ELSE 'fractional' END;",
        solutionSql: "SELECT CASE WHEN 7 / 2 = 3 THEN 'integer' ELSE 'fractional' END;",
        answerOptions: [
          { id: 'a', label: 'integer', value: 'integer' },
          { id: 'b', label: 'fractional', value: 'fractional' },
          { id: 'c', label: 'NULL', value: 'NULL' },
        ], correctAnswerId: 'a' },
      { kind: 'answer', title: 'Cancelled orders',
        prompt: 'How many orders were cancelled? Use a conditional total to investigate.',
        solutionSql: "SELECT SUM(CASE WHEN status = 'cancelled' THEN 1 ELSE 0 END) FROM orders;" },
      { kind: 'match', title: 'Fulfillment snapshot',
        prompt: 'Recreate the target row of shipped and pending order counts.',
        solutionSql: "SELECT COUNT(*) FILTER (WHERE status = 'shipped') AS shipped, COUNT(*) FILTER (WHERE status = 'pending') AS pending FROM orders;" },
      { kind: 'bug', title: 'Everything looks shipped',
        prompt: 'The summary counts every order as shipped. Repair the calculation.',
        starterSql: "SELECT SUM(CASE WHEN status = 'shipped' THEN 1 ELSE 1 END) AS shipped_count FROM orders;",
        solutionSql: "SELECT SUM(CASE WHEN status = 'shipped' THEN 1 ELSE 0 END) AS shipped_count FROM orders;" },
      { kind: 'write', title: 'City operations board', difficulty: 'boss',
        prompt: 'For each customer city, show shipped and cancelled order counts, including cities with zero of either.',
        solutionSql: "SELECT c.city, COUNT(o.id) FILTER (WHERE o.status = 'shipped') AS shipped_orders, COUNT(o.id) FILTER (WHERE o.status = 'cancelled') AS cancelled_orders FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.city;",
        hint: 'Keep every customer city, then count order IDs separately for each status.' },
    ],
    exam: [
      ['Shipment labels', 'Show each order ID with a shipped or not-shipped label.',
        "SELECT id, CASE WHEN status = 'shipped' THEN 'shipped' ELSE 'not shipped' END AS label FROM orders;"],
      ['Two order totals', 'Show pending and cancelled order counts in one row.',
        "SELECT COUNT(*) FILTER (WHERE status = 'pending') AS pending, COUNT(*) FILTER (WHERE status = 'cancelled') AS cancelled FROM orders;"],
      ['Product tiers', 'Show product names and a low or high label split at price 10.',
        "SELECT name, CASE WHEN price < 10 THEN 'low' ELSE 'high' END AS price_tier FROM products;"],
      ['Paid status count', 'For each order state, count orders that have a payment.',
        'SELECT o.status, COUNT(DISTINCT o.id) FILTER (WHERE p.id IS NOT NULL) AS paid_orders FROM orders o LEFT JOIN payments p ON p.order_id = o.id GROUP BY o.status;'],
      ['City split', 'Recreate the target city table with shipped order counts.',
        "SELECT c.city, COUNT(o.id) FILTER (WHERE o.status = 'shipped') AS shipped FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.city;"],
      ['Category premium counts', 'Recreate the target count of premium products per category.',
        'SELECT category, COUNT(*) FILTER (WHERE price >= 20) AS premium_count FROM products GROUP BY category;'],
      ['Shipped total', 'How many orders have shipped?',
        "SELECT COUNT(*) FILTER (WHERE status = 'shipped') FROM orders;"],
      ['Standard stock', 'How many products cost less than 20?',
        'SELECT SUM(CASE WHEN price < 20 THEN 1 ELSE 0 END) FROM products;'],
    ],
  }),
  makeLevel({
    number: 9, id: 'outer-joins', title: 'Keep the missing rows',
    subtitle: 'Use outer joins, anti-joins, and careful totals.', skill: 'outerJoin',
    rules: [
      { title: 'Keep the left side', body: 'LEFT JOIN retains rows even when there is no match on the right. Put a condition on the right table in ON; in WHERE it removes the unmatched rows again.',
        example: "SELECT c.id, o.id\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id AND o.status = 'shipped';" },
      { title: 'Find what is absent', body: 'A missing right-side key after an outer join identifies unmatched rows.',
        example: 'WHERE o.id IS NULL' },
      { title: 'Avoid multiplying amounts', body: 'Two one-to-many joins can multiply each other. Summarize each child table first: put that summary in parentheses (a subquery), give it an alias, and join to it like a table.',
        example: 'SELECT order_id, units FROM (SELECT order_id, SUM(quantity) AS units FROM order_items GROUP BY order_id) AS i;' },
    ],
    practice: [
      { kind: 'write', title: 'Customers with no orders',
        prompt: 'Find customer IDs and names for people who have never bought anything.',
        solutionSql: 'SELECT c.id, c.name FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.id IS NULL;' },
      { kind: 'complete', title: 'Include zero-order customers',
        prompt: 'Count orders for every customer, including people with none.',
        solutionSql: 'SELECT c.id, COUNT(o.id) AS order_count FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.id;',
        templateParts: ['SELECT c.id, ', ' AS order_count FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.id;'],
        blankLabels: ['safe order count'], blankAnswers: ['COUNT(o.id)'] },
      { kind: 'predict', title: 'One empty join row',
        prompt: 'How many rows does this outer join count for customer 10?',
        starterSql: 'SELECT COUNT(*) FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE c.id = 10;',
        solutionSql: 'SELECT COUNT(*) FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE c.id = 10;',
        answerOptions: [
          { id: 'a', label: '0', value: '0' }, { id: 'b', label: '1', value: '1' },
          { id: 'c', label: '2', value: '2' },
        ], correctAnswerId: 'b', hint: 'An unmatched left row still appears once.' },
      { kind: 'answer', title: 'Never sold',
        prompt: 'How many products have never appeared on an order item?',
        solutionSql: 'SELECT COUNT(*) FROM products p LEFT JOIN order_items oi ON oi.product_id = p.id WHERE oi.id IS NULL;' },
      { kind: 'match', title: 'Sales including zero',
        prompt: 'Recreate the target product table, including products with no sales.',
        solutionSql: 'SELECT p.id, p.name, COALESCE(SUM(oi.quantity), 0) AS units FROM products p LEFT JOIN order_items oi ON oi.product_id = p.id GROUP BY p.id, p.name;' },
      { kind: 'bug', title: 'Disappearing customers',
        prompt: 'The shipped-order report loses customers with zero shipments. Repair its logic.',
        starterSql: "SELECT c.id, COUNT(o.id) AS shipped_count FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.status = 'shipped' GROUP BY c.id;",
        solutionSql: "SELECT c.id, COUNT(o.id) AS shipped_count FROM customers c LEFT JOIN orders o ON o.customer_id = c.id AND o.status = 'shipped' GROUP BY c.id;",
        commonMistakes: [{
          sql: "SELECT c.id, COUNT(o.id) AS shipped_count FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.status = 'shipped' GROUP BY c.id;",
          feedback: 'Filtering the right table in WHERE removes unmatched customers. Put the shipment condition in ON.',
        }] },
      { id: 'l9-p8', kind: 'bug', title: 'One order that never happened',
        prompt: 'The customer with no orders shows a count of one. Repair the count.',
        starterSql: 'SELECT c.id, COUNT(*) AS order_count FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.id;',
        solutionSql: 'SELECT c.id, COUNT(o.id) AS order_count FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.id;',
        commonMistakes: [{
          sql: 'SELECT c.id, COUNT(*) AS order_count FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.id;',
          feedback: 'COUNT(*) counts the unmatched customer row. Count o.id to get zero orders.',
        }] },
      { id: 'l9-p9', kind: 'bug', title: 'Two buyers merged together',
        prompt: 'Two different buyers share a name. Keep their order counts separate.',
        starterSql: 'SELECT c.name, COUNT(o.id) AS order_count FROM customers c JOIN orders o ON o.customer_id = c.id GROUP BY c.name;',
        solutionSql: 'SELECT c.id, c.name, COUNT(o.id) AS order_count FROM customers c JOIN orders o ON o.customer_id = c.id GROUP BY c.id, c.name;',
        commonMistakes: [{
          sql: 'SELECT c.name, COUNT(o.id) AS order_count FROM customers c JOIN orders o ON o.customer_id = c.id GROUP BY c.name;',
          feedback: 'Names are not unique. Group by customer ID so the two Ava Chen records stay separate.',
        }] },
      { kind: 'write', title: 'Payment reconciliation', difficulty: 'boss',
        id: 'l9-p7',
        prompt: 'For the first three orders, show each order ID, item total, and payment total without inflating either amount.',
        solutionSql: 'SELECT o.id, COALESCE(i.item_total, 0) AS item_total, COALESCE(p.paid_total, 0) AS paid_total FROM orders o LEFT JOIN (SELECT oi.order_id, SUM(oi.quantity * pr.price) AS item_total FROM order_items oi JOIN products pr ON pr.id = oi.product_id GROUP BY oi.order_id) i ON i.order_id = o.id LEFT JOIN (SELECT order_id, SUM(amount) AS paid_total FROM payments GROUP BY order_id) p ON p.order_id = o.id WHERE o.id <= 3;',
        hint: 'Summarize line items and payments separately before joining them to orders.' },
    ],
    exam: [
      ['Unsold product IDs', 'Show IDs of products that have never sold.',
        'SELECT p.id FROM products p LEFT JOIN order_items oi ON oi.product_id = p.id WHERE oi.id IS NULL;'],
      ['All customer order totals', 'Show every customer ID with its order count, including zero.',
        'SELECT c.id, COUNT(o.id) AS order_count FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.id;'],
      ['Orders without payments', 'Show IDs of orders that have no payment record.',
        'SELECT o.id FROM orders o LEFT JOIN payments p ON p.order_id = o.id WHERE p.id IS NULL;'],
      ['Product category paths', 'Show each product name and its category name from the category table.',
        'SELECT p.name, c.name AS category_name FROM products p JOIN categories c ON c.id = p.category_id;'],
      ['Never bought', 'Recreate the target customer table for people with no orders.',
        'SELECT c.id, c.name FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.id IS NULL;'],
      ['All product counts', 'Recreate the target item-count table for all products.',
        'SELECT p.id, COUNT(oi.id) AS item_rows FROM products p LEFT JOIN order_items oi ON oi.product_id = p.id GROUP BY p.id;'],
      ['Unpaid count', 'How many orders have no payment record?',
        'SELECT COUNT(*) FROM orders o LEFT JOIN payments p ON p.order_id = o.id WHERE p.id IS NULL;'],
      ['Unreviewed stock', 'How many products have never been reviewed?',
        'SELECT COUNT(*) FROM products p LEFT JOIN reviews r ON r.product_id = p.id WHERE r.id IS NULL;'],
    ],
  }),
  makeLevel({
    number: 10, id: 'subqueries', title: 'Ask a question inside a question',
    subtitle: 'Compare against summaries and test whether related rows exist.', skill: 'subquery',
    rules: [
      { title: 'Compare with a scalar', body: 'A single-value subquery can supply a threshold for the outer query, or a value for each row when it refers to the outer row.',
        example: 'SELECT name FROM products WHERE price > (SELECT AVG(price) FROM products);\nSELECT c.id, (SELECT COUNT(*) FROM orders o WHERE o.customer_id = c.id) AS order_count FROM customers c;' },
      { title: 'Test existence', body: 'EXISTS checks whether a related row can be found. NOT EXISTS works for missing relationships.',
        example: 'WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id)' },
      { title: 'Be careful with NOT IN', body: 'A NULL in the returned list can make NOT IN match nothing. NOT EXISTS is safer for anti-joins.',
        example: 'WHERE c.id NOT IN (SELECT customer_id FROM orders)\nWHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id)' },
    ],
    practice: [
      { kind: 'write', title: 'Above the shop average',
        prompt: 'Find names and prices of products that cost more than the average product.',
        solutionSql: 'SELECT name, price FROM products WHERE price > (SELECT AVG(price) FROM products);' },
      { kind: 'complete', title: 'Customers who bought',
        prompt: 'Show customers who have at least one order.',
        solutionSql: 'SELECT c.id, c.name FROM customers c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);',
        templateParts: ['SELECT c.id, c.name FROM customers c WHERE ', ' (SELECT 1 FROM orders o WHERE o.customer_id = c.id);'],
        blankLabels: ['existence test'], blankAnswers: ['EXISTS'] },
      { kind: 'predict', title: 'The hidden NULL',
        prompt: 'How many customers survive this exclusion?',
        starterSql: 'SELECT COUNT(*) FROM customers WHERE id NOT IN (SELECT referred_by FROM customers);',
        solutionSql: 'SELECT COUNT(*) FROM customers WHERE id NOT IN (SELECT referred_by FROM customers);',
        answerOptions: [
          { id: 'a', label: '0', value: '0' }, { id: 'b', label: '1', value: '1' },
          { id: 'c', label: '3', value: '3' },
        ], correctAnswerId: 'a', hint: 'The excluded list contains a missing value.' },
      { kind: 'answer', title: 'Customers who never ordered',
        prompt: 'How many customers have no orders?',
        solutionSql: 'SELECT COUNT(*) FROM customers c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);' },
      { kind: 'match', title: 'Last order per customer',
        prompt: 'Recreate the target table showing each of the first five customers’ most recent order date.',
        solutionSql: 'SELECT c.id, (SELECT MAX(o.order_date) FROM orders o WHERE o.customer_id = c.id) AS last_order FROM customers c WHERE c.id <= 5 ORDER BY c.id;' },
      { kind: 'bug', title: 'No referral candidates',
        prompt: 'The report should find customers who referred nobody, but it is empty. Repair the exclusion.',
        starterSql: 'SELECT c.id FROM customers c WHERE c.id NOT IN (SELECT referred_by FROM customers);',
        solutionSql: 'SELECT c.id FROM customers c WHERE NOT EXISTS (SELECT 1 FROM customers r WHERE r.referred_by = c.id);',
        commonMistakes: [{
          sql: 'SELECT c.id FROM customers c WHERE c.id NOT IN (SELECT referred_by FROM customers);',
          feedback: 'The referral list contains NULL, which breaks NOT IN. Use NOT EXISTS.',
        }] },
      { kind: 'explain', title: 'Decipher the threshold subquery',
        prompt: 'Study the query below. Which plain-English description correctly explains what it produces?',
        hint: 'Observe the subquery in the WHERE clause calculating an average.',
        explanation: 'The query returns products whose individual price is strictly higher than the average price of all products.',
        starterSql: 'SELECT name, price FROM products WHERE price > (SELECT AVG(price) FROM products);',
        solutionSql: 'SELECT name, price FROM products WHERE price > (SELECT AVG(price) FROM products);',
        answerOptions: [
          { id: 'a', label: 'Returns products whose price exceeds the shop-wide average product price.' },
          { id: 'b', label: 'Returns products whose category average is higher than the overall average.' },
          { id: 'c', label: 'Calculates the difference between each product and the cheapest product.' },
          { id: 'd', label: 'Finds the single most expensive product in the catalog.' },
        ],
        correctAnswerId: 'a' },
      { kind: 'write', title: 'Above-average repeat buyers', difficulty: 'boss',
        prompt: 'Show customer IDs and order counts for buyers whose count exceeds the average among buyers.',
        solutionSql: 'SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id HAVING COUNT(*) > (SELECT AVG(order_count) FROM (SELECT COUNT(*) AS order_count FROM orders GROUP BY customer_id) counts);',
        hint: 'Build the per-customer counts, then compare each count with their average.' },
    ],
    exam: [
      ['Below-average products', 'Show names and prices of products cheaper than the shop average.',
        'SELECT name, price FROM products WHERE price < (SELECT AVG(price) FROM products);'],
      ['No-order customers', 'Show IDs and names of customers who have never ordered.',
        'SELECT c.id, c.name FROM customers c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id);'],
      ['Reviewed products', 'Show product IDs and names for products with at least one review.',
        'SELECT p.id, p.name FROM products p WHERE EXISTS (SELECT 1 FROM reviews r WHERE r.product_id = p.id);'],
      ['Largest orders by units', 'Show order IDs whose item quantity total exceeds the average order quantity total.',
        'SELECT order_id FROM order_items GROUP BY order_id HAVING SUM(quantity) > (SELECT AVG(units) FROM (SELECT SUM(quantity) AS units FROM order_items GROUP BY order_id) totals);'],
      ['Unsold names', 'Recreate the target table of unsold product names.',
        'SELECT p.name FROM products p WHERE NOT EXISTS (SELECT 1 FROM order_items oi WHERE oi.product_id = p.id);'],
      ['Customer last dates', 'Recreate the target table of last order dates for the first five customers.',
        'SELECT c.id, (SELECT MAX(order_date) FROM orders o WHERE o.customer_id = c.id) AS last_order FROM customers c WHERE c.id <= 5 ORDER BY c.id;'],
      ['Products above average', 'How many products cost more than the average?',
        'SELECT COUNT(*) FROM products WHERE price > (SELECT AVG(price) FROM products);'],
      ['Buyers with reviews', 'How many customers have written at least one review?',
        'SELECT COUNT(*) FROM customers c WHERE EXISTS (SELECT 1 FROM reviews r WHERE r.customer_id = c.id);'],
    ],
  }),
  makeLevel({
    number: 11, id: 'ctes', title: 'Make complex work readable',
    subtitle: 'Name intermediate results and walk a hierarchy.', skill: 'cte',
    rules: [
      { title: 'Name a working result', body: 'WITH gives a temporary name to a query that the final query can read.',
        example: 'WITH totals AS (SELECT order_id, SUM(quantity) AS units FROM order_items GROUP BY order_id) SELECT * FROM totals;' },
      { title: 'Build in steps', body: 'Several CTEs can each solve one part of a larger question. Write WITH once and separate the CTEs with commas.',
        example: 'WITH items AS (SELECT order_id, SUM(quantity) AS units FROM order_items GROUP BY order_id),\n     big AS (SELECT order_id FROM items WHERE units >= 3)\nSELECT * FROM big;' },
      { title: 'Repeat a step', body: 'WITH RECURSIVE runs a starting query, then repeats a second query on the rows just found until no new rows appear. UNION ALL joins the two parts.',
        example: 'WITH RECURSIVE n(x) AS (SELECT 1 UNION ALL SELECT x + 1 FROM n WHERE x < 3) SELECT * FROM n;' },
      { title: 'Walk parent-child links', body: 'To walk a hierarchy, start from the top rows, then JOIN each child to the rows found so far.',
        example: 'WITH RECURSIVE tree AS (\n  SELECT id, name FROM categories WHERE parent_id IS NULL\n  UNION ALL\n  SELECT c.id, c.name FROM categories c JOIN tree t ON c.parent_id = t.id\n)\nSELECT * FROM tree;' },
    ],
    practice: [
      { kind: 'write', title: 'Named item totals',
        prompt: 'Build a named intermediate result of item quantities per order, then show its rows.',
        solutionSql: 'WITH totals AS (SELECT order_id, SUM(quantity) AS units FROM order_items GROUP BY order_id) SELECT order_id, units FROM totals;',
        requiredPatterns: [{ pattern: '\\bWITH\\b', label: 'a WITH clause' }] },
      { kind: 'complete', title: 'Start the working result',
        prompt: 'Complete the opening keyword for a named order count.',
        solutionSql: 'WITH counts AS (SELECT customer_id, COUNT(*) AS orders FROM orders GROUP BY customer_id) SELECT * FROM counts;',
        templateParts: ['', ' counts AS (SELECT customer_id, COUNT(*) AS orders FROM orders GROUP BY customer_id) SELECT * FROM counts;'],
        blankLabels: ['opening keyword'], blankAnswers: ['WITH'] },
      { kind: 'predict', title: 'Recursive count',
        prompt: 'What is the largest number generated here?',
        starterSql: 'WITH RECURSIVE n(x) AS (SELECT 1 UNION ALL SELECT x + 1 FROM n WHERE x < 3) SELECT MAX(x) FROM n;',
        solutionSql: 'WITH RECURSIVE n(x) AS (SELECT 1 UNION ALL SELECT x + 1 FROM n WHERE x < 3) SELECT MAX(x) FROM n;',
        answerOptions: [
          { id: 'a', label: '2', value: '2' }, { id: 'b', label: '3', value: '3' },
          { id: 'c', label: '4', value: '4' },
        ], correctAnswerId: 'b' },
      { kind: 'answer', title: 'Referral family',
        prompt: 'How many customers are in customer 1’s referral tree, including customer 1?',
        solutionSql: 'WITH RECURSIVE referrals AS (SELECT id FROM customers WHERE id = 1 UNION ALL SELECT c.id FROM customers c JOIN referrals r ON c.referred_by = r.id) SELECT COUNT(*) FROM referrals;' },
      { kind: 'match', title: 'Category depths',
        prompt: 'Recreate the target table of category names and depths from the root.',
        solutionSql: 'WITH RECURSIVE tree(id, name, depth) AS (SELECT id, name, 1 FROM categories WHERE parent_id IS NULL UNION ALL SELECT c.id, c.name, t.depth + 1 FROM categories c JOIN tree t ON c.parent_id = t.id) SELECT name, depth FROM tree ORDER BY depth, name;' },
      { kind: 'bug', title: 'Pieces are not units',
        prompt: 'The named result counts item rows instead of item quantities. Correct it.',
        starterSql: 'WITH totals AS (SELECT order_id, COUNT(*) AS units FROM order_items GROUP BY order_id) SELECT order_id, units FROM totals;',
        solutionSql: 'WITH totals AS (SELECT order_id, SUM(quantity) AS units FROM order_items GROUP BY order_id) SELECT order_id, units FROM totals;' },
      { kind: 'refactor', title: 'Refactor subquery to CTE',
        prompt: 'Refactor this nested subquery query into a clean, readable CTE using WITH.',
        hint: 'Define a WITH clause named totals, then SELECT from it.',
        explanation: 'Extracting nested subqueries into named CTEs makes queries modular and readable.',
        starterSql: 'SELECT order_id, units FROM (SELECT order_id, SUM(quantity) AS units FROM order_items GROUP BY order_id) sub WHERE units >= 3 ORDER BY units DESC, order_id ASC;',
        solutionSql: 'WITH totals AS (\n  SELECT order_id, SUM(quantity) AS units\n  FROM order_items\n  GROUP BY order_id\n)\nSELECT order_id, units\nFROM totals\nWHERE units >= 3\nORDER BY units DESC, order_id ASC;',
        requiredPatterns: [{ pattern: '\\bWITH\\b', label: 'a WITH (CTE) clause' }],
        forbiddenPatterns: [{ pattern: 'FROM\\s*\\(', label: 'subquery in FROM clause' }],
        orderMatters: true },
      { kind: 'write', title: 'The category family', difficulty: 'boss',
        prompt: 'Show every category with its depth and number of directly assigned products, including empty branches.',
        solutionSql: 'WITH RECURSIVE tree AS (SELECT id, name, parent_id, 1 AS depth FROM categories WHERE parent_id IS NULL UNION ALL SELECT c.id, c.name, c.parent_id, t.depth + 1 FROM categories c JOIN tree t ON c.parent_id = t.id) SELECT t.name, t.depth, COUNT(p.id) AS products FROM tree t LEFT JOIN products p ON p.category_id = t.id GROUP BY t.id, t.name, t.depth;',
        requiredPatterns: [{ pattern: '\\bWITH\\s+RECURSIVE\\b', label: 'a recursive CTE' }] },
    ],
    exam: [
      ['Named customer counts', 'Use a named working result to show orders per customer.',
        'WITH counts AS (SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id) SELECT customer_id, order_count FROM counts;'],
      ['Named paid totals', 'Use a named working result to show payment total per order.',
        'WITH paid AS (SELECT order_id, SUM(amount) AS paid_total FROM payments GROUP BY order_id) SELECT order_id, paid_total FROM paid;'],
      ['Referral steps', 'Show customer IDs and their distance from customer 1 in the referral family.',
        'WITH RECURSIVE family(id, depth) AS (SELECT id, 0 FROM customers WHERE id = 1 UNION ALL SELECT c.id, f.depth + 1 FROM customers c JOIN family f ON c.referred_by = f.id) SELECT id, depth FROM family;'],
      ['Category ancestors', 'Show category IDs and depths for every category under the root.',
        'WITH RECURSIVE tree(id, depth) AS (SELECT id, 1 FROM categories WHERE parent_id IS NULL UNION ALL SELECT c.id, t.depth + 1 FROM categories c JOIN tree t ON c.parent_id = t.id) SELECT id, depth FROM tree;'],
      ['Three generated numbers', 'Recreate the target sequence from one through three.',
        'WITH RECURSIVE n(x) AS (SELECT 1 UNION ALL SELECT x + 1 FROM n WHERE x < 3) SELECT x FROM n;'],
      ['Tree sizes', 'Recreate the target category depth counts.',
        'WITH RECURSIVE tree(id, depth) AS (SELECT id, 1 FROM categories WHERE parent_id IS NULL UNION ALL SELECT c.id, t.depth + 1 FROM categories c JOIN tree t ON c.parent_id = t.id) SELECT depth, COUNT(*) AS categories FROM tree GROUP BY depth;'],
      ['Tree size', 'How many categories exist in the rooted category tree?',
        'WITH RECURSIVE tree(id) AS (SELECT id FROM categories WHERE parent_id IS NULL UNION ALL SELECT c.id FROM categories c JOIN tree t ON c.parent_id = t.id) SELECT COUNT(*) FROM tree;'],
      ['Deepest level', 'What is the greatest category depth?',
        'WITH RECURSIVE tree(id, depth) AS (SELECT id, 1 FROM categories WHERE parent_id IS NULL UNION ALL SELECT c.id, t.depth + 1 FROM categories c JOIN tree t ON c.parent_id = t.id) SELECT MAX(depth) FROM tree;'],
    ],
  }),
  makeLevel({
    number: 12, id: 'dates', title: 'Follow the calendar',
    subtitle: 'Group time, compare periods, and keep empty months visible.', skill: 'dates',
    rules: [
      { title: 'Choose a period', body: 'date_trunc groups timestamps or dates into a month, week, or day. It returns a timestamp; add ::date to show just the date.',
        example: "SELECT date_trunc('month', order_date)::date AS month FROM orders;" },
      { title: 'Read a date part', body: 'EXTRACT gets the year, month, or another part of a date.',
        example: 'SELECT EXTRACT(YEAR FROM order_date) FROM orders;' },
      { title: 'Include the last day', body: 'For timestamp ranges, use a closed start and open end.',
        example: "WHERE shipped_at >= '2026-01-01' AND shipped_at < '2026-02-01'" },
      { title: 'Count the days between dates', body: 'Subtracting one date from another gives the number of days between them. Cast a timestamp to a date first with ::date.',
        example: "SELECT id, paid_at::date - DATE '2026-01-01' AS days_in FROM payments;" },
      { title: 'Fill in empty periods', body: 'generate_series(start, stop, step) makes one row per period, such as every week. LEFT JOIN your data to it so periods with no events stay visible.',
        example: "SELECT week::date FROM generate_series('2026-01-05'::date, '2026-02-02'::date, INTERVAL '1 week') AS week;" },
    ],
    practice: [
      { kind: 'write', title: 'Monthly order counts',
        prompt: 'Show the number of orders in each month represented in the data.',
        solutionSql: "SELECT date_trunc('month', order_date)::date AS month, COUNT(*) AS order_count FROM orders GROUP BY 1;" },
      { kind: 'complete', title: 'Order years',
        prompt: 'Show the calendar year of every order.',
        solutionSql: 'SELECT id, EXTRACT(YEAR FROM order_date) AS order_year FROM orders;',
        templateParts: ['SELECT id, EXTRACT(', ' FROM order_date) AS order_year FROM orders;'],
        blankLabels: ['date part'], blankAnswers: ['YEAR'] },
      { kind: 'predict', title: 'One day apart',
        prompt: 'How many days separate these dates?',
        starterSql: "SELECT DATE '2026-03-01' - DATE '2026-02-28';",
        solutionSql: "SELECT DATE '2026-03-01' - DATE '2026-02-28';",
        answerOptions: [
          { id: 'a', label: '1', value: '1' }, { id: 'b', label: '2', value: '2' },
          { id: 'c', label: '28', value: '28' },
        ], correctAnswerId: 'a' },
      { kind: 'answer', title: 'Orders in March',
        prompt: 'How many orders were placed during March 2026?',
        solutionSql: "SELECT COUNT(*) FROM orders WHERE order_date >= '2026-03-01' AND order_date < '2026-04-01';" },
      { kind: 'match', title: 'Monthly shipped counts',
        prompt: 'Recreate the target monthly counts for shipped orders.',
        solutionSql: "SELECT date_trunc('month', order_date)::date AS month, COUNT(*) AS shipped FROM orders WHERE status = 'shipped' GROUP BY 1 ORDER BY 1;" },
      { kind: 'bug', title: 'Last-day shipments missing',
        prompt: 'The January shipment report loses events late on the final day. Correct the time window.',
        starterSql: "SELECT id FROM orders WHERE shipped_at BETWEEN '2026-01-01' AND '2026-01-31';",
        solutionSql: "SELECT id FROM orders WHERE shipped_at >= '2026-01-01' AND shipped_at < '2026-02-01';",
        commonMistakes: [{
          sql: "SELECT id FROM orders WHERE shipped_at BETWEEN '2026-01-01' AND '2026-01-31';",
          feedback: 'The upper timestamp is midnight at the start of January 31. Use an exclusive February 1 end.',
        }] },
      { kind: 'write', title: 'Show the quiet months', difficulty: 'boss',
        prompt: 'Show monthly order counts from December 2025 through March 2026, including months with no orders.',
        solutionSql: "SELECT month::date AS month, COUNT(o.id) AS order_count FROM generate_series('2025-12-01'::date, '2026-03-01'::date, INTERVAL '1 month') AS month LEFT JOIN orders o ON date_trunc('month', o.order_date) = month GROUP BY month ORDER BY month;",
        hint: 'Generate the months first, then keep each one while matching orders.' },
    ],
    exam: [
      ['Order years', 'Show each calendar year and its order count.',
        'SELECT EXTRACT(YEAR FROM order_date) AS year, COUNT(*) AS order_count FROM orders GROUP BY 1;'],
      ['January shipments', 'Show IDs of orders shipped during January 2026, including the final day.',
        "SELECT id FROM orders WHERE shipped_at >= '2026-01-01' AND shipped_at < '2026-02-01';"],
      ['Days from order to shipment', 'Show each shipped order ID and days until shipment.',
        "SELECT id, (shipped_at::date - order_date) AS days_to_ship FROM orders WHERE shipped_at IS NOT NULL;"],
      ['First quarter orders', 'Show order IDs placed in the first three months of 2026.',
        "SELECT id FROM orders WHERE order_date >= '2026-01-01' AND order_date < '2026-04-01';"],
      ['Monthly volume', 'Recreate the target monthly order-count table.',
        "SELECT date_trunc('month', order_date)::date AS month, COUNT(*) AS orders FROM orders GROUP BY 1 ORDER BY 1;"],
      ['Shipment months', 'Recreate the target count of shipments per month.',
        "SELECT date_trunc('month', shipped_at)::date AS month, COUNT(*) AS shipments FROM orders WHERE shipped_at IS NOT NULL GROUP BY 1 ORDER BY 1;"],
      ['January orders', 'How many orders were placed in January 2026?',
        "SELECT COUNT(*) FROM orders WHERE order_date >= '2026-01-01' AND order_date < '2026-02-01';"],
      ['Unique order months', 'How many different calendar months contain orders?',
        "SELECT COUNT(DISTINCT date_trunc('month', order_date)) FROM orders;"],
    ],
  }),
  makeLevel({
    number: 13, id: 'window-rank', title: 'Rank without losing rows',
    subtitle: 'Find leaders within each group and understand ties.', skill: 'windowRank',
    rules: [
      { title: 'Look across a window', body: 'OVER computes a value across related rows while keeping each row visible.',
        example: 'SELECT name, RANK() OVER (ORDER BY price DESC) FROM products;' },
      { title: 'Restart within groups', body: 'PARTITION BY gives each group its own ranking.',
        example: 'RANK() OVER (PARTITION BY category ORDER BY price DESC)' },
      { title: 'Know what ties do', body: 'ROW_NUMBER always differs; RANK leaves gaps after ties; DENSE_RANK does not.',
        example: 'SELECT name, price,\n       ROW_NUMBER() OVER (ORDER BY price DESC) AS row_no,\n       RANK() OVER (ORDER BY price DESC) AS rnk,\n       DENSE_RANK() OVER (ORDER BY price DESC) AS dense_rnk\nFROM products;' },
      { title: 'Keep only the leaders', body: 'A window result cannot be used in WHERE directly. Put the ranking in a subquery, then filter its alias in the outer query.',
        example: 'SELECT product_id, id AS latest_review\nFROM (\n  SELECT product_id, id, ROW_NUMBER() OVER (PARTITION BY product_id ORDER BY created_at DESC, id DESC) AS rn\n  FROM reviews\n) ranked\nWHERE rn = 1;' },
    ],
    practice: [
      { kind: 'write', title: 'Rank category prices',
        prompt: 'Show each product ID, category, and its price rank within that category. Equal prices share a rank.',
        solutionSql: 'SELECT id, category, DENSE_RANK() OVER (PARTITION BY category ORDER BY price DESC) AS price_rank FROM products;',
        requiredPatterns: [{ pattern: '\\bOVER\\s*\\(', label: 'a window function' }] },
      { kind: 'complete', title: 'Number customer orders',
        prompt: 'Give each customer’s orders a sequence from newest to oldest.',
        solutionSql: 'SELECT id, customer_id, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date DESC, id DESC) AS sequence FROM orders;',
        templateParts: ['SELECT id, customer_id, ', ' OVER (PARTITION BY customer_id ORDER BY order_date DESC, id DESC) AS sequence FROM orders;'],
        blankLabels: ['row numbering function'], blankAnswers: ['ROW_NUMBER()'] },
      { kind: 'predict', title: 'A tied top price',
        prompt: 'What rank does product 1 receive when only these tied products are considered?',
        starterSql: 'SELECT price_rank FROM (SELECT id, RANK() OVER (ORDER BY price DESC) AS price_rank FROM products WHERE id IN (1, 11)) ranked WHERE id = 1;',
        solutionSql: 'SELECT price_rank FROM (SELECT id, RANK() OVER (ORDER BY price DESC) AS price_rank FROM products WHERE id IN (1, 11)) ranked WHERE id = 1;',
        answerOptions: [
          { id: 'a', label: '1', value: '1' }, { id: 'b', label: '2', value: '2' },
          { id: 'c', label: '3', value: '3' },
        ], correctAnswerId: 'a' },
      { kind: 'answer', title: 'Gear price positions',
        prompt: 'How many distinct price ranks exist in the Gear category?',
        solutionSql: "SELECT MAX(price_rank) FROM (SELECT DENSE_RANK() OVER (ORDER BY price DESC) AS price_rank FROM products WHERE category = 'Gear') ranked;" },
      { kind: 'match', title: 'Category leaders',
        prompt: 'Recreate the target table of the most expensive product in each category.',
        solutionSql: 'SELECT category, name, price FROM (SELECT category, name, price, ROW_NUMBER() OVER (PARTITION BY category ORDER BY price DESC, name) AS rn FROM products) ranked WHERE rn = 1;' },
      { kind: 'bug', title: 'Ties lost their rank',
        prompt: 'Equal prices should share a ranking position. Correct the running query.',
        starterSql: 'SELECT id, ROW_NUMBER() OVER (ORDER BY price DESC) AS position FROM products;',
        solutionSql: 'SELECT id, RANK() OVER (ORDER BY price DESC) AS position FROM products;',
        hint: 'Choose the ranking function that gives ties the same number.',
        commonMistakes: [{
          sql: 'SELECT id, ROW_NUMBER() OVER (ORDER BY price DESC) AS position FROM products;',
          feedback: 'ROW_NUMBER gives tied prices different positions. Use RANK for shared positions.',
        }] },
      { id: 'l13-p8', kind: 'bug', title: 'A tied winner disappeared',
        prompt: 'The top-price report shows one tied product and hides the other. Keep every tied winner.',
        starterSql: 'SELECT name, price FROM products WHERE price <= 8 ORDER BY price DESC LIMIT 1;',
        solutionSql: 'SELECT name, price FROM (SELECT name, price, RANK() OVER (ORDER BY price DESC) AS rnk FROM products WHERE price <= 8) ranked WHERE rnk = 1;',
        commonMistakes: [{
          sql: 'SELECT name, price FROM products WHERE price <= 8 ORDER BY price DESC LIMIT 1;',
          feedback: 'LIMIT 1 arbitrarily keeps one row from a price tie. Rank and keep all first-place rows.',
        }] },
      { kind: 'write', title: 'Two leaders per category', difficulty: 'boss',
        id: 'l13-p7',
        prompt: 'Show products in the two highest price ranks of each category, including any price ties.',
        solutionSql: 'SELECT category, name, price FROM (SELECT category, name, price, DENSE_RANK() OVER (PARTITION BY category ORDER BY price DESC) AS price_rank FROM products) ranked WHERE price_rank <= 2;',
        hint: 'Rank within each category, then filter the ranked result.' },
    ],
    exam: [
      ['Global price ranks', 'Show product IDs and price ranks across the shop, allowing ties.',
        'SELECT id, RANK() OVER (ORDER BY price DESC) AS price_rank FROM products;'],
      ['Newest order positions', 'Show each order ID, customer ID, and recency position for that customer.',
        'SELECT id, customer_id, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date DESC, id DESC) AS recency FROM orders;'],
      ['Dense price groups', 'Show each product ID and its dense price rank.',
        'SELECT id, DENSE_RANK() OVER (ORDER BY price DESC) AS price_rank FROM products;'],
      ['First review per product', 'Show each review ID and its sequence within the product.',
        'SELECT id, product_id, ROW_NUMBER() OVER (PARTITION BY product_id ORDER BY created_at, id) AS review_number FROM reviews;'],
      ['Most recent per customer', 'Recreate the target table of the latest order per customer.',
        'SELECT customer_id, id AS order_id FROM (SELECT customer_id, id, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date DESC, id DESC) AS rn FROM orders) ranked WHERE rn = 1;'],
      ['Category winners', 'Recreate the target table of the highest-price product in each category.',
        'SELECT category, name FROM (SELECT category, name, ROW_NUMBER() OVER (PARTITION BY category ORDER BY price DESC, name) AS rn FROM products) ranked WHERE rn = 1;'],
      ['Price ranks', 'How many distinct price ranks are there across products?',
        'SELECT MAX(rnk) FROM (SELECT DENSE_RANK() OVER (ORDER BY price DESC) AS rnk FROM products) ranked;'],
      ['Tied eights', 'How many products share the price of product 1?',
        'SELECT COUNT(*) FROM products WHERE price = (SELECT price FROM products WHERE id = 1);'],
    ],
  }),
  makeLevel({
    number: 14, id: 'window-trend', title: 'See what changed',
    subtitle: 'Running totals, prior rows, and period comparisons.', skill: 'windowTrend',
    rules: [
      { title: 'Accumulate over time', body: 'A window SUM with an ordered ROWS frame builds a running total.',
        example: 'SUM(amount) OVER (ORDER BY paid_at ROWS UNBOUNDED PRECEDING)' },
      { title: 'Look back or ahead', body: 'LAG reads an earlier row; LEAD reads a later row in the chosen order.',
        example: 'LAG(amount) OVER (ORDER BY paid_at)\nLEAD(amount) OVER (ORDER BY paid_at)' },
      { title: 'Compare periods', body: 'Summarize each period first, then use a window to compare neighboring periods.',
        example: 'LAG(order_count) OVER (ORDER BY month)' },
    ],
    practice: [
      { kind: 'write', title: 'Running payment total',
        prompt: 'Show each payment ID, amount, and cumulative amount in payment-time order.',
        solutionSql: 'SELECT id, amount, SUM(amount) OVER (ORDER BY paid_at, id ROWS UNBOUNDED PRECEDING) AS running_total FROM payments;',
        requiredPatterns: [{ pattern: '\\bOVER\\s*\\(', label: 'a window function' }] },
      { kind: 'complete', title: 'Previous payment',
        prompt: 'Show each payment with the amount immediately before it in payment-time order.',
        solutionSql: 'SELECT id, LAG(amount) OVER (ORDER BY paid_at, id) AS previous_amount FROM payments;',
        templateParts: ['SELECT id, ', '(amount) OVER (ORDER BY paid_at, id) AS previous_amount FROM payments;'],
        blankLabels: ['look-back function'], blankAnswers: ['LAG'] },
      { kind: 'predict', title: 'Running total at the end',
        prompt: 'What is the final cumulative value?',
        starterSql: 'SELECT SUM(x) OVER (ORDER BY x ROWS UNBOUNDED PRECEDING) FROM (VALUES (1), (2), (3)) t(x) ORDER BY x DESC LIMIT 1;',
        solutionSql: 'SELECT SUM(x) OVER (ORDER BY x ROWS UNBOUNDED PRECEDING) FROM (VALUES (1), (2), (3)) t(x) ORDER BY x DESC LIMIT 1;',
        answerOptions: [
          { id: 'a', label: '3', value: '3' }, { id: 'b', label: '5', value: '5' },
          { id: 'c', label: '6', value: '6' },
        ], correctAnswerId: 'c' },
      { kind: 'answer', title: 'Previous amount for payment two',
        prompt: 'What amount was paid immediately before payment 2?',
        solutionSql: 'SELECT previous_amount FROM (SELECT id, LAG(amount) OVER (ORDER BY paid_at, id) AS previous_amount FROM payments) p WHERE id = 2;' },
      { kind: 'match', title: 'First five order positions',
        prompt: 'Recreate the target timeline of the first five orders and their sequence numbers.',
        solutionSql: 'SELECT id, order_date, ROW_NUMBER() OVER (ORDER BY order_date, id) AS sequence FROM orders ORDER BY order_date, id LIMIT 5;' },
      { kind: 'bug', title: 'Total is not running',
        prompt: 'The amount repeats for all payments on an order. Make it cumulative instead.',
        starterSql: 'SELECT id, amount, SUM(amount) OVER (PARTITION BY order_id) AS running_total FROM payments;',
        solutionSql: 'SELECT id, amount, SUM(amount) OVER (ORDER BY paid_at, id ROWS UNBOUNDED PRECEDING) AS running_total FROM payments;' },
      { kind: 'write', title: 'Month-over-month growth', difficulty: 'boss',
        prompt: 'Show each active month’s order count, prior active month’s count, and percentage change rounded to two decimals.',
        solutionSql: "WITH monthly AS (SELECT date_trunc('month', order_date)::date AS month, COUNT(*) AS order_count FROM orders GROUP BY 1), compared AS (SELECT month, order_count, LAG(order_count) OVER (ORDER BY month) AS prior_count FROM monthly) SELECT month, order_count, prior_count, ROUND(100.0 * (order_count - prior_count) / NULLIF(prior_count, 0), 2) AS growth_pct FROM compared;",
        hint: 'Summarize months, look back one row, then calculate the change.' },
    ],
    exam: [
      ['Running unit count', 'Show item IDs, quantities, and cumulative quantity by item ID.',
        'SELECT id, quantity, SUM(quantity) OVER (ORDER BY id ROWS UNBOUNDED PRECEDING) AS running_units FROM order_items;'],
      ['Prior order date', 'Show each order ID with the date of the previous order in date order.',
        'SELECT id, LAG(order_date) OVER (ORDER BY order_date, id) AS prior_date FROM orders;'],
      ['Next payment', 'Show each payment ID and the amount paid next in payment-time order.',
        'SELECT id, LEAD(amount) OVER (ORDER BY paid_at, id) AS next_amount FROM payments;'],
      ['Customer running units', 'Show each order item ID, order ID, and cumulative units within its order.',
        'SELECT id, order_id, SUM(quantity) OVER (PARTITION BY order_id ORDER BY id ROWS UNBOUNDED PRECEDING) AS running_units FROM order_items;'],
      ['First payment steps', 'Recreate the target running-total table for the first five payments.',
        'SELECT id, SUM(amount) OVER (ORDER BY paid_at, id ROWS UNBOUNDED PRECEDING) AS running_paid FROM payments ORDER BY paid_at, id LIMIT 5;'],
      ['Order date neighbors', 'Recreate the target table of the first five orders and prior dates.',
        'SELECT id, LAG(order_date) OVER (ORDER BY order_date, id) AS prior_date FROM orders ORDER BY order_date, id LIMIT 5;'],
      ['Total payments', 'What is the final running payment total?',
        'SELECT MAX(running_total) FROM (SELECT SUM(amount) OVER (ORDER BY paid_at, id ROWS UNBOUNDED PRECEDING) AS running_total FROM payments) p;'],
      ['Largest single payment', 'What is the largest payment amount?',
        'SELECT MAX(amount) FROM payments;'],
    ],
  }),
  makeLevel({
    number: 15, id: 'sets-and-strings', title: 'Combine and describe',
    subtitle: 'Set operations and compact text summaries.', skill: 'sets',
    rules: [
      { title: 'Combine sets', body: 'UNION removes duplicates across matching result shapes; UNION ALL retains them.',
        example: 'SELECT city AS label FROM customers UNION SELECT category FROM products;' },
      { title: 'Find overlap or difference', body: 'INTERSECT keeps shared rows. EXCEPT keeps rows from the first set that are absent from the second.',
        example: 'SELECT product_id FROM reviews INTERSECT SELECT product_id FROM order_items;\nSELECT id FROM customers EXCEPT SELECT customer_id FROM orders;' },
      { title: 'Describe a group', body: 'string_agg combines text values within each group; ordering inside it makes the output stable. left(text, n) returns the first n characters.',
        example: "SELECT category, string_agg(name, ', ' ORDER BY name) FROM products GROUP BY category;\nSELECT left(name, 1) AS initial, COUNT(*) FROM products GROUP BY left(name, 1);" },
    ],
    practice: [
      { kind: 'write', title: 'Place and product labels',
        prompt: 'Make one list of customer city names and product category names, each label only once.',
        solutionSql: 'SELECT city AS label FROM customers UNION SELECT category AS label FROM products;' },
      { kind: 'complete', title: 'Customers who bought',
        prompt: 'Find customer IDs that appear both in the customer list and in orders.',
        solutionSql: 'SELECT id FROM customers INTERSECT SELECT customer_id FROM orders;',
        templateParts: ['SELECT id FROM customers ', ' SELECT customer_id FROM orders;'],
        blankLabels: ['set overlap operator'], blankAnswers: ['INTERSECT'] },
      { kind: 'predict', title: 'Unique numbers',
        prompt: 'How many rows remain after this combination?',
        starterSql: 'SELECT COUNT(*) FROM (SELECT 1 AS n UNION SELECT 1 UNION SELECT 2) numbers;',
        solutionSql: 'SELECT COUNT(*) FROM (SELECT 1 AS n UNION SELECT 1 UNION SELECT 2) numbers;',
        answerOptions: [
          { id: 'a', label: '1', value: '1' }, { id: 'b', label: '2', value: '2' },
          { id: 'c', label: '3', value: '3' },
        ], correctAnswerId: 'b' },
      { kind: 'answer', title: 'Customer IDs with no orders',
        prompt: 'How many customer IDs are absent from the order list?',
        solutionSql: 'SELECT COUNT(*) FROM (SELECT id FROM customers EXCEPT SELECT customer_id FROM orders) missing;' },
      { kind: 'match', title: 'Category name rollup',
        prompt: 'Recreate the target list of product names grouped into category text.',
        solutionSql: "SELECT category, string_agg(name, ', ' ORDER BY name) AS product_names FROM products GROUP BY category;" },
      { kind: 'bug', title: 'Repeated cities',
        prompt: 'The combined list has duplicate city names. Repair the set operation.',
        starterSql: 'SELECT city AS label FROM customers UNION ALL SELECT city AS label FROM customers;',
        solutionSql: 'SELECT city AS label FROM customers UNION SELECT city AS label FROM customers;' },
      { kind: 'write', title: 'Unsold shelf labels', difficulty: 'boss',
        prompt: 'For each category with unsold products, show the category and an alphabetized comma-separated list of their names.',
        solutionSql: "SELECT category, string_agg(name, ', ' ORDER BY name) AS unsold_names FROM products WHERE id IN (SELECT id FROM products EXCEPT SELECT product_id FROM order_items) GROUP BY category;",
        hint: 'Find unsold IDs first, then group their names by category.' },
    ],
    exam: [
      ['All place labels', 'Show one distinct list of customer cities and product categories.',
        'SELECT city AS label FROM customers UNION SELECT category AS label FROM products;'],
      ['Customers without orders', 'Show customer IDs absent from the order list.',
        'SELECT id FROM customers EXCEPT SELECT customer_id FROM orders;'],
      ['Bought customer IDs', 'Show customer IDs present in both customers and orders.',
        'SELECT id FROM customers INTERSECT SELECT customer_id FROM orders;'],
      ['Names by category', 'Show each category and a sorted comma-separated list of product names.',
        "SELECT category, string_agg(name, ', ' ORDER BY name) AS names FROM products GROUP BY category;"],
      ['Status labels', 'Recreate the target distinct status labels from orders and a literal other label.',
        "SELECT status AS label FROM orders UNION SELECT 'other' AS label;"],
      ['Customer initials', 'Recreate the target table of first letters and the names in each group.',
        "SELECT left(name, 1) AS initial, string_agg(name, ', ' ORDER BY name) AS names FROM customers GROUP BY left(name, 1);"],
      ['Unsold count', 'How many product IDs have never appeared on an order item?',
        'SELECT COUNT(*) FROM (SELECT id FROM products EXCEPT SELECT product_id FROM order_items) unsold;'],
      ['Distinct city count', 'How many unique customer cities are there?',
        'SELECT COUNT(*) FROM (SELECT city FROM customers UNION SELECT city FROM customers) cities;'],
    ],
  }),
  makeLevel({
    number: 16, id: 'analyst-capstones', title: 'Think like an analyst',
    subtitle: 'Put the whole toolkit to work on realistic reports.', skill: 'capstone',
    rules: [
      { title: 'Start with the grain', body: 'Decide what one result row represents before joining or summarizing.',
        example: 'SELECT customer_id, COUNT(*) AS orders FROM orders GROUP BY customer_id;' },
      { title: 'Stage each calculation', body: 'Build cohort, funnel, and revenue inputs separately; then combine them at their shared grain.',
        example: 'WITH monthly AS (SELECT date_trunc(\'month\', order_date) AS month FROM orders) SELECT * FROM monthly;' },
      { title: 'Audit edge cases', body: 'Check missing matches, duplicate names, partial payments, and tied values before trusting a report.',
        example: 'SELECT order_id, SUM(amount) FROM payments GROUP BY order_id;' },
    ],
    practice: [
      { kind: 'write', title: 'Signup cohorts',
        prompt: 'Show the number of customers who signed up in each calendar month.',
        solutionSql: "SELECT date_trunc('month', signup_date)::date AS cohort_month, COUNT(*) AS customers FROM customers GROUP BY 1;" },
      { kind: 'complete', title: 'Funnel reach',
        prompt: 'Show total customers, customers who ordered, and orders that received a payment.',
        solutionSql: 'SELECT COUNT(DISTINCT c.id) AS customers, COUNT(DISTINCT o.customer_id) AS buyers, COUNT(DISTINCT p.order_id) AS paid_orders FROM customers c LEFT JOIN orders o ON o.customer_id = c.id LEFT JOIN payments p ON p.order_id = o.id;',
        templateParts: ['SELECT COUNT(', ' c.id) AS customers, COUNT(DISTINCT o.customer_id) AS buyers, COUNT(DISTINCT p.order_id) AS paid_orders FROM customers c LEFT JOIN orders o ON o.customer_id = c.id LEFT JOIN payments p ON p.order_id = o.id;'],
        blankLabels: ['deduplication keyword'], blankAnswers: ['DISTINCT'] },
      { kind: 'predict', title: 'First three order IDs',
        prompt: 'How many rows does this small audit return?',
        starterSql: 'SELECT COUNT(*) FROM orders WHERE id <= 3;',
        solutionSql: 'SELECT COUNT(*) FROM orders WHERE id <= 3;',
        answerOptions: [
          { id: 'a', label: '2', value: '2' }, { id: 'b', label: '3', value: '3' },
          { id: 'c', label: '4', value: '4' },
        ], correctAnswerId: 'b' },
      { kind: 'answer', title: 'How many signup months?',
        prompt: 'How many calendar months have at least one customer signup?',
        solutionSql: "SELECT COUNT(DISTINCT date_trunc('month', signup_date)) FROM customers;" },
      { kind: 'match', title: 'Latest order per buyer',
        prompt: 'Recreate the target table showing the latest order for each customer who ordered.',
        solutionSql: 'SELECT id, customer_id, order_date FROM (SELECT o.*, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date DESC, id DESC) AS rn FROM orders o) latest WHERE rn = 1;' },
      { kind: 'bug', title: 'Payments doubled by items',
        prompt: 'The paid amount for order 1 is inflated. Repair the report’s row grain.',
        starterSql: 'SELECT o.id, SUM(p.amount) AS paid_total FROM orders o JOIN payments p ON p.order_id = o.id JOIN order_items oi ON oi.order_id = o.id WHERE o.id = 1 GROUP BY o.id;',
        solutionSql: 'SELECT o.id, SUM(p.amount) AS paid_total FROM orders o JOIN payments p ON p.order_id = o.id WHERE o.id = 1 GROUP BY o.id;',
        commonMistakes: [{
          sql: 'SELECT o.id, SUM(p.amount) AS paid_total FROM orders o JOIN payments p ON p.order_id = o.id JOIN order_items oi ON oi.order_id = o.id WHERE o.id = 1 GROUP BY o.id;',
          feedback: 'Joining payments to item rows repeats each payment. Sum payments at the order grain.',
        }] },
      { kind: 'write', title: 'Monthly revenue investigation', difficulty: 'boss',
        prompt: 'For each order month and status, show the total item value and total paid amount without double counting.',
        solutionSql: "WITH items AS (SELECT oi.order_id, SUM(oi.quantity * pr.price) AS item_total FROM order_items oi JOIN products pr ON pr.id = oi.product_id GROUP BY oi.order_id), paid AS (SELECT order_id, SUM(amount) AS paid_total FROM payments GROUP BY order_id) SELECT date_trunc('month', o.order_date)::date AS month, o.status, SUM(COALESCE(i.item_total, 0)) AS item_value, SUM(COALESCE(p.paid_total, 0)) AS paid_value FROM orders o LEFT JOIN items i ON i.order_id = o.id LEFT JOIN paid p ON p.order_id = o.id GROUP BY 1, o.status;",
        hint: 'Total items and payments at order grain before grouping by month and status.' },
    ],
    exam: [
      ['Signup month report', 'Show customer counts by signup month.',
        "SELECT date_trunc('month', signup_date)::date AS month, COUNT(*) AS signups FROM customers GROUP BY 1;"],
      ['Buyer funnel', 'Show total customers and the number who have ever ordered.',
        'SELECT COUNT(*) AS customers, COUNT(*) FILTER (WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id)) AS buyers FROM customers c;'],
      ['Latest orders', 'Show each buyer ID and latest order date.',
        'SELECT customer_id, MAX(order_date) AS latest_order FROM orders GROUP BY customer_id;'],
      ['Payment gaps', 'Show order IDs whose total payments are below their item totals.',
        'WITH items AS (SELECT oi.order_id, SUM(oi.quantity * p.price) AS total FROM order_items oi JOIN products p ON p.id = oi.product_id GROUP BY oi.order_id), paid AS (SELECT order_id, SUM(amount) AS total FROM payments GROUP BY order_id) SELECT i.order_id FROM items i LEFT JOIN paid p ON p.order_id = i.order_id WHERE COALESCE(p.total, 0) < i.total;'],
      ['Cohort sizes', 'Recreate the target customer count by signup year.',
        'SELECT EXTRACT(YEAR FROM signup_date) AS year, COUNT(*) AS customers FROM customers GROUP BY 1;'],
      ['Status totals', 'Recreate the target order count by year and status.',
        'SELECT EXTRACT(YEAR FROM order_date) AS year, status, COUNT(*) AS orders FROM orders GROUP BY 1, status;'],
      ['Paid orders', 'How many distinct orders have at least one payment?',
        'SELECT COUNT(DISTINCT order_id) FROM payments;'],
      ['Unpaid orders', 'How many orders have no payment record?',
        'SELECT COUNT(*) FROM orders o WHERE NOT EXISTS (SELECT 1 FROM payments p WHERE p.order_id = o.id);'],
    ],
  }),
];
