import type { Exercise, ExerciseOption, Level, SkillId } from './schema';

export const SKILL_LABELS: Record<SkillId, string> = {
  select: 'Selecting columns',
  filter: 'Filtering rows',
  sort: 'Sorting results',
  aggregate: 'Grouping and totals',
  join: 'Joining tables',
  distinct: 'Unique rows and calculations',
  conditions: 'Flexible conditions',
  nulls: 'Missing values',
  case: 'Conditional logic',
  outerJoin: 'Keeping unmatched rows',
  subquery: 'Subqueries',
  cte: 'Common table expressions',
  dates: 'Dates and trends',
  windowRank: 'Ranking within groups',
  windowTrend: 'Running and prior values',
  sets: 'Set and string operations',
  capstone: 'Analyst investigations',
};

type ChoiceInput = Pick<
  Exercise,
  'id' | 'skill' | 'title' | 'prompt' | 'hint' | 'explanation' | 'orderMatters'
> & {
  options: ExerciseOption[];
  correctOptionId: string;
};

/** Keeps the chosen answer and SQL used by the grader in sync. */
function choose(input: ChoiceInput): Exercise {
  const answer = input.options.find((option) => option.id === input.correctOptionId);
  if (!answer) throw new Error(`No correct option for ${input.id}`);
  return { ...input, kind: 'choose', solutionSql: answer.sql };
}

export const LEVELS: Level[] = [
  {
    id: 'select',
    number: 1,
    title: 'Find your way around',
    subtitle: 'Read columns from the shop tables.',
    skills: ['select'],
    rules: [
      {
        title: 'Ask for columns',
        body: 'SELECT names the columns you want, separated by commas. FROM names the table they come from.',
        example: 'SELECT name, price FROM products;',
      },
      {
        title: 'Use * to explore',
        body: 'An asterisk returns every column. It is handy when you first inspect a table.',
        example: 'SELECT * FROM customers;',
      },
      {
        title: 'Build one clause at a time',
        body: 'Start with SELECT, add FROM, then end the statement with a semicolon. Later you will add WHERE after FROM to keep only the rows you want.',
        example: 'SELECT id, status FROM orders WHERE id = 1;',
      },
    ],
    exercises: [
      {
        id: 'l1-p1', kind: 'write', skill: 'select',
        title: 'Product names',
        prompt: 'Write a query that shows the name of every product.',
        hint: 'Read the name column from products.',
        explanation: 'SELECT chooses name; FROM points to products.',
        solutionSql: 'SELECT name FROM products;',
      },
      choose({
        id: 'l1-p2', skill: 'select', title: 'Explore customers',
        prompt: 'Which query shows every column in the customers table?',
        hint: 'The * symbol means all columns.',
        explanation: 'SELECT * returns all columns from the named table.',
        options: [
          { id: 'a', sql: 'SELECT name FROM customers;' },
          { id: 'b', sql: 'SELECT * FROM customers;' },
          { id: 'c', sql: 'SELECT * FROM products;' },
          { id: 'd', sql: 'SELECT id, name FROM customers;' },
        ],
        correctOptionId: 'b',
      }),
      {
        id: 'l1-p3', kind: 'complete', skill: 'select',
        title: 'Two product columns',
        prompt: 'Complete the query to show each product name and price.',
        hint: 'The missing column is price.',
        explanation: 'Separate column names with a comma.',
        solutionSql: 'SELECT name, price FROM products;',
        templateParts: ['SELECT name, ', ' FROM products;'],
        blankLabels: ['second column'],
        blankAnswers: ['price'],
      },
      {
        id: 'l1-p4', kind: 'fix', skill: 'select',
        title: 'Repair a keyword',
        prompt: 'Fix the query so it shows customer IDs and names.',
        hint: 'Check the spelling of the first keyword.',
        explanation: 'SELECT must be spelled exactly for SQL to read the query.',
        starterSql: 'SELCT id, name FROM customers;',
        solutionSql: 'SELECT id, name FROM customers;',
      },
      {
        id: 'l1-p5', kind: 'write', skill: 'select',
        title: 'Order status',
        prompt: 'Show the id and status of every order.',
        hint: 'Both columns live in orders.',
        explanation: 'You can request multiple columns in one SELECT list.',
        solutionSql: 'SELECT id, status FROM orders;',
      },
      choose({
        id: 'l1-p6', skill: 'select', title: 'Only categories',
        prompt: 'Which query shows only the category column for all products?',
        hint: 'The table is products, and the only selected column is category.',
        explanation: 'Select just category when that is the only information requested.',
        options: [
          { id: 'a', sql: 'SELECT name FROM products;' },
          { id: 'b', sql: 'SELECT category, name FROM products;' },
          { id: 'c', sql: 'SELECT category FROM products;' },
          { id: 'd', sql: 'SELECT category FROM products WHERE price > 20;' },
        ],
        correctOptionId: 'c',
      }),
      {
        id: 'l1-p7', kind: 'predict', skill: 'select',
        title: 'Read the result first',
        prompt: 'What single price will this query return? Inspect the products table on the right (or click "View products table data" below).',
        hint: 'Inspect the products table to find the row with id = 1, then read its price.',
        explanation: 'In the products table, the row with id = 1 (Notebook) has a price of 8.00.',
        starterSql: 'SELECT price FROM products WHERE id = 1;',
        solutionSql: 'SELECT price FROM products WHERE id = 1;',
        answerOptions: [
          { id: 'a', label: '8.00', value: '8' },
          { id: 'b', label: '9.00', value: '9' },
          { id: 'c', label: '12.00', value: '12' },
          { id: 'd', label: '35.00', value: '35' },
        ],
        correctAnswerId: 'a',
      },
      {
        id: 'l1-p8', kind: 'write', skill: 'select', difficulty: 'boss',
        title: 'Stockroom inventory card',
        prompt: 'The stockroom needs every product’s ID, name, category, and price on one card.',
        hint: 'All four details live on each product row.',
        explanation: 'Select the four requested product columns in the requested order.',
        solutionSql: 'SELECT id, name, category, price FROM products;',
      },
    ],
    exam: [
      {
        id: 'l1-e1', kind: 'write', skill: 'select',
        title: 'Customer locations',
        prompt: 'Show the name and city of every customer.',
        hint: 'Both columns are in customers.',
        explanation: 'List name and city before FROM customers.',
        solutionSql: 'SELECT name, city FROM customers;',
      },
      {
        id: 'l1-e2', kind: 'complete', skill: 'select',
        title: 'Order dates',
        prompt: 'Fill in the missing column to show each order ID and its date.',
        hint: 'The date column is order_date.',
        explanation: 'The orders table stores its date in order_date.',
        solutionSql: 'SELECT id, order_date FROM orders;',
        templateParts: ['SELECT id, ', ' FROM orders;'],
        blankLabels: ['date column'],
        blankAnswers: ['order_date'],
      },
      {
        id: 'l1-e3', kind: 'fix', skill: 'select',
        title: 'Find the table typo',
        prompt: 'Fix the query so it shows every product name and price.',
        hint: 'The table is called products, with an s.',
        explanation: 'A table name in FROM must match the actual table name.',
        starterSql: 'SELECT name, price FROM product;',
        solutionSql: 'SELECT name, price FROM products;',
      },
      choose({
        id: 'l1-e4', skill: 'select', title: 'Product identifiers',
        prompt: 'Which query shows the ID and name of every product?',
        hint: 'Read both columns from products.',
        explanation: 'Both requested columns belong to products.',
        options: [
          { id: 'a', sql: 'SELECT id, name FROM customers;' },
          { id: 'b', sql: 'SELECT name FROM products;' },
          { id: 'c', sql: 'SELECT id, name FROM products;' },
          { id: 'd', sql: 'SELECT name, id FROM products;' },
        ],
        correctOptionId: 'c',
      }),
      {
        id: 'l1-e5', kind: 'write', skill: 'select',
        title: 'Product prices',
        prompt: 'Show the price of every product.',
        hint: 'Read price from products.',
        explanation: 'SELECT price returns one value for each product.',
        solutionSql: 'SELECT price FROM products;',
      },
      {
        id: 'l1-e6', kind: 'complete', skill: 'select',
        title: 'Customer names',
        prompt: 'Fill in the table name to show every customer name.',
        hint: 'Customer records live in customers.',
        explanation: 'FROM customers points to the customer table.',
        solutionSql: 'SELECT name FROM customers;',
        templateParts: ['SELECT name FROM ', ';'],
        blankLabels: ['table name'],
        blankAnswers: ['customers'],
      },
      {
        id: 'l1-e7', kind: 'fix', skill: 'select',
        title: 'Wrong table',
        prompt: 'Fix the query to show the ID and status of every order.',
        hint: 'Status is a column of orders.',
        explanation: 'Read both requested columns from orders.',
        starterSql: 'SELECT id, status FROM products;',
        solutionSql: 'SELECT id, status FROM orders;',
      },
      choose({
        id: 'l1-e8', skill: 'select', title: 'Order owners',
        prompt: 'Which query shows only the customer ID for every order?',
        hint: 'The orders table stores customer_id.',
        explanation: 'The selected column names the customer who placed the order.',
        options: [
          { id: 'a', sql: 'SELECT customer_id FROM orders;' },
          { id: 'b', sql: 'SELECT id FROM customers;' },
          { id: 'c', sql: 'SELECT id FROM orders;' },
          { id: 'd', sql: 'SELECT customer_id, id FROM orders;' },
        ],
        correctOptionId: 'a',
      }),
    ],
    examDrawCount: 4,
    passCount: 3,
  },
  {
    id: 'filter-sort',
    number: 2,
    title: 'Find the right rows',
    subtitle: 'Filter results and put them in order.',
    skills: ['filter', 'sort'],
    rules: [
      {
        title: 'Filter with WHERE',
        body: 'WHERE keeps only rows that meet a condition. Text values go in single quotes.',
        example: "SELECT name FROM customers WHERE city = 'Boston';",
      },
      {
        title: 'Combine conditions',
        body: 'AND requires both conditions to be true. Comparisons work with numbers and dates: <, <=, >, >= and <> (not equal).',
        example: "SELECT id FROM orders WHERE status = 'shipped' AND order_date >= '2026-01-10';",
      },
      {
        title: 'Sort with ORDER BY',
        body: 'ASC sorts low to high; DESC sorts high to low. Add more columns after commas to break ties. ORDER BY comes after WHERE.',
        example: 'SELECT name, price FROM products ORDER BY price DESC, name ASC;',
      },
    ],
    exercises: [
      {
        id: 'l2-p1', kind: 'write', skill: 'filter',
        title: 'Higher-priced products',
        prompt: 'Show names and prices of products costing at least {min}, most expensive first.',
        hint: 'Use price >= {min}, then ORDER BY price DESC.',
        explanation: 'WHERE filters the products before ORDER BY sorts them.',
        solutionSql: 'SELECT name, price FROM products WHERE price >= {min} ORDER BY price DESC;',
        orderMatters: true,
        params: {
          min: { pick: [18, 20, 22] },
        },
      },
      choose({
        id: 'l2-p2', skill: 'filter', title: 'Boston customers',
        prompt: 'Which query shows the names of every customer in Boston?',
        hint: "Compare city with the text 'Boston'.",
        explanation: 'The WHERE condition tests the city, while SELECT keeps only names.',
        options: [
          { id: 'a', sql: "SELECT name FROM customers WHERE city = 'Austin';" },
          { id: 'b', sql: "SELECT city FROM customers WHERE city = 'Boston';" },
          { id: 'c', sql: "SELECT name FROM customers WHERE city = 'Boston';" },
          { id: 'd', sql: "SELECT name FROM customers WHERE city <> 'Boston';" },
        ],
        correctOptionId: 'c',
      }),
      {
        id: 'l2-p3', kind: 'complete', skill: 'filter',
        title: 'Shipped orders',
        prompt: 'Fill in the status value to show IDs and customer IDs of shipped orders.',
        hint: 'The status is shipped.',
        explanation: 'Text values in a WHERE comparison need single quotes.',
        solutionSql: "SELECT id, customer_id FROM orders WHERE status = 'shipped';",
        templateParts: ["SELECT id, customer_id FROM orders WHERE status = '", "';"],
        blankLabels: ['status value'],
        blankAnswers: ['shipped'],
      },
      {
        id: 'l2-p4', kind: 'fix', skill: 'sort',
        title: 'Cheapest first',
        prompt: 'Fix the sort direction to show product names and prices from cheapest to most expensive.',
        hint: 'ASC means ascending.',
        explanation: 'ORDER BY price ASC starts with the lowest price; name breaks price ties.',
        starterSql: 'SELECT name, price FROM products ORDER BY price DESC, name ASC;',
        solutionSql: 'SELECT name, price FROM products ORDER BY price ASC, name ASC;',
        orderMatters: true,
      },
      {
        id: 'l2-p5', kind: 'write', skill: 'filter',
        title: 'Recent shipped orders',
        prompt: 'Show the ID and date of shipped orders dated January 10, 2026 or later, earliest first.',
        hint: "Use status = 'shipped' AND order_date >= '2026-01-10'.",
        explanation: 'AND narrows to rows meeting both conditions; ASC orders their dates.',
        solutionSql: "SELECT id, order_date FROM orders WHERE status = 'shipped' AND order_date >= '2026-01-10' ORDER BY order_date ASC;",
        orderMatters: true,
        commonMistakes: [{
          sql: "SELECT id, order_date FROM orders WHERE status = 'shipped' AND order_date >= '2026-01-10';",
          feedback: 'The rows are right, but the timeline needs an explicit earliest-first sort.',
        }],
      },
      choose({
        id: 'l2-p6', skill: 'filter', title: 'Affordable stationery',
        prompt: 'Which query shows names of Stationery products priced below 10?',
        hint: 'Both the category and price conditions must hold.',
        explanation: 'AND makes each returned product meet both requirements.',
        options: [
          { id: 'a', sql: "SELECT name FROM products WHERE category = 'Stationery' OR price < 10;" },
          { id: 'b', sql: "SELECT name FROM products WHERE category = 'Stationery' AND price < 10;" },
          { id: 'c', sql: "SELECT name FROM products WHERE category = 'Stationery' AND price > 10;" },
          { id: 'd', sql: "SELECT name FROM products WHERE category = 'Gear' AND price < 10;" },
        ],
        correctOptionId: 'b',
      }),
      {
        id: 'l2-p7', kind: 'answer', skill: 'filter',
        title: 'Find order seven',
        prompt: 'A support agent needs the status of order 7. Explore the data, then enter the status word.',
        hint: 'Find the row whose order ID is 7.',
        explanation: 'Order 7 is still pending.',
        solutionSql: 'SELECT status FROM orders WHERE id = 7;',
      },
      {
        id: 'l2-p8', kind: 'write', skill: 'filter', difficulty: 'boss',
        title: '{category} display shortlist',
        prompt: 'Show names and prices of {category} products costing at least {min}, most expensive first.',
        hint: 'Combine the category and price rules, then sort the survivors.',
        explanation: 'The category and price conditions narrow the rows before sorting.',
        solutionSql: "SELECT name, price FROM products WHERE category = '{category}' AND price >= {min} ORDER BY price DESC, name ASC;",
        orderMatters: true,
        params: {
          category: { pick: ['Home', 'Gear'], fromSql: 'SELECT DISTINCT category FROM products' },
          min: { pick: [10, 15] },
        },
      },
      {
        id: 'l2-p9', kind: 'order', skill: 'sort',
        title: 'Price list clause order',
        prompt: 'Arrange the clauses in the correct order to list Home product names and prices sorted from cheapest to most expensive.',
        hint: 'Standard SQL order is SELECT, then FROM, then WHERE, then ORDER BY.',
        explanation: 'SQL requires clauses in the syntactic order: SELECT -> FROM -> WHERE -> ORDER BY.',
        clauses: [
          'SELECT name, price',
          'FROM products',
          "WHERE category = 'Home'",
          'ORDER BY price ASC, name ASC;',
        ],
        solutionSql: "SELECT name, price\nFROM products\nWHERE category = 'Home'\nORDER BY price ASC, name ASC;",
        orderMatters: true,
      },
    ],
    exam: [
      {
        id: 'l2-e1', kind: 'write', skill: 'sort',
        title: 'Gear, low to high',
        prompt: 'Show names and prices of Gear products, from lowest to highest price.',
        hint: "Filter category = 'Gear', then sort price ASC.",
        explanation: 'WHERE chooses Gear rows and ORDER BY sets the requested order.',
        solutionSql: "SELECT name, price FROM products WHERE category = 'Gear' ORDER BY price ASC;",
        orderMatters: true,
      },
      choose({
        id: 'l2-e2', skill: 'sort', title: 'Newest pending orders',
        prompt: 'Which query shows pending order IDs and dates, newest first?',
        hint: 'Filter pending orders, then sort date DESC.',
        explanation: 'DESC puts the newest date first.',
        options: [
          { id: 'a', sql: "SELECT id, order_date FROM orders WHERE status = 'pending' ORDER BY order_date ASC;" },
          { id: 'b', sql: "SELECT id, order_date FROM orders WHERE status = 'pending' ORDER BY order_date DESC;" },
          { id: 'c', sql: "SELECT id, order_date FROM orders WHERE status = 'shipped' ORDER BY order_date DESC;" },
          { id: 'd', sql: "SELECT id FROM orders WHERE status = 'pending' ORDER BY order_date DESC;" },
        ],
        correctOptionId: 'b', orderMatters: true,
      }),
      {
        id: 'l2-e3', kind: 'fix', skill: 'filter',
        title: 'Above twenty',
        prompt: 'Fix the comparison to show products costing more than 20.',
        hint: 'More than excludes 20 itself.',
        explanation: '> means strictly more than; <= means 20 or less.',
        starterSql: 'SELECT name, price FROM products WHERE price <= 20;',
        solutionSql: 'SELECT name, price FROM products WHERE price > 20;',
      },
      {
        id: 'l2-e4', kind: 'complete', skill: 'filter',
        title: 'Pending order IDs',
        prompt: 'Fill in the status to show IDs for pending orders.',
        hint: 'The status value is pending.',
        explanation: 'WHERE status narrows the orders to pending rows.',
        solutionSql: "SELECT id FROM orders WHERE status = 'pending';",
        templateParts: ["SELECT id FROM orders WHERE status = '", "';"],
        blankLabels: ['status'],
        blankAnswers: ['pending'],
      },
      {
        id: 'l2-e5', kind: 'write', skill: 'sort',
        title: 'Latest orders',
        prompt: 'Show every order ID and date, latest date first.',
        hint: 'Sort by order_date descending.',
        explanation: 'ORDER BY order_date DESC puts the newest order first.',
        solutionSql: 'SELECT id, order_date FROM orders ORDER BY order_date DESC;',
        orderMatters: true,
      },
      {
        id: 'l2-e6', kind: 'fix', skill: 'filter',
        title: 'Boston only',
        prompt: 'Fix the condition to show the names of Boston customers.',
        hint: 'Match city to Boston.',
        explanation: 'WHERE city selects only matching customers.',
        starterSql: "SELECT name FROM customers WHERE city = 'Austin';",
        solutionSql: "SELECT name FROM customers WHERE city = 'Boston';",
      },
      choose({
        id: 'l2-e7', skill: 'filter', title: 'Shipped in January',
        prompt: 'Which query shows IDs of shipped orders placed on or after January 10, 2026?',
        hint: 'Both conditions must be true.',
        explanation: 'AND keeps only shipped orders in the date range.',
        options: [
          { id: 'a', sql: "SELECT id FROM orders WHERE status = 'shipped' OR order_date >= '2026-01-10';" },
          { id: 'b', sql: "SELECT id FROM orders WHERE status = 'pending' AND order_date >= '2026-01-10';" },
          { id: 'c', sql: "SELECT id FROM orders WHERE status = 'shipped' AND order_date >= '2026-01-10';" },
          { id: 'd', sql: "SELECT id FROM orders WHERE status = 'shipped' AND order_date < '2026-01-10';" },
        ],
        correctOptionId: 'c',
      }),
      {
        id: 'l2-e8', kind: 'write', skill: 'filter',
        title: 'Budget products',
        prompt: 'Show names and prices of products costing less than 10.',
        hint: 'Filter price below 10.',
        explanation: 'A strict comparison excludes products priced exactly 10.',
        solutionSql: 'SELECT name, price FROM products WHERE price < 10;',
      },
    ],
    examDrawCount: 4,
    passCount: 3,
  },
  {
    id: 'aggregate',
    number: 3,
    title: 'Count and compare',
    subtitle: 'Turn many rows into useful totals.',
    skills: ['aggregate'],
    rules: [
      {
        title: 'Summarize many rows',
        body: 'COUNT(*) counts rows; COUNT(column) counts rows where that column has a value. SUM adds a numeric column and AVG averages it. MIN and MAX find the smallest and largest value. Use AS to name each result.',
        example: 'SELECT COUNT(*) AS payment_count,\n       SUM(amount) AS total_paid,\n       AVG(amount) AS avg_paid,\n       MIN(amount) AS smallest,\n       MAX(amount) AS largest\nFROM payments;',
      },
      {
        title: 'Make groups',
        body: 'Without GROUP BY, an aggregate summarizes the whole table into one row. GROUP BY creates one result per distinct group. Any plain column you select beside an aggregate belongs in GROUP BY. Different rows can share a name, so include the unique ID when each one needs its own result.',
        example: 'SELECT status, COUNT(*) AS order_count FROM orders GROUP BY status;',
      },
      {
        title: 'Filter groups with HAVING',
        body: 'WHERE filters individual rows; HAVING filters finished groups.',
        example: 'SELECT customer_id FROM orders GROUP BY customer_id HAVING COUNT(*) > 1;',
      },
    ],
    exercises: [
      {
        id: 'l3-p1', kind: 'write', skill: 'aggregate',
        title: 'How many orders?',
        prompt: 'Return one row with the number of orders, named order_count.',
        hint: 'COUNT(*) counts rows in orders.',
        explanation: 'An aggregate without GROUP BY summarizes the whole table.',
        solutionSql: 'SELECT COUNT(*) AS order_count FROM orders;',
        commonMistakes: [{
          sql: 'SELECT COUNT(*) FROM orders;',
          feedback: 'The count is right. Name the output column order_count.',
        }],
      },
      choose({
        id: 'l3-p2', skill: 'aggregate', title: 'Orders by status',
        prompt: 'Which query returns each order status and its order_count?',
        hint: 'Group orders by status before counting.',
        explanation: 'GROUP BY status produces one count per status.',
        options: [
          { id: 'a', sql: 'SELECT status, COUNT(*) AS order_count FROM orders GROUP BY status;' },
          { id: 'b', sql: 'SELECT COUNT(*) AS order_count FROM orders;' },
          { id: 'c', sql: 'SELECT status FROM orders GROUP BY status;' },
          { id: 'd', sql: 'SELECT status, COUNT(*) AS order_count FROM orders GROUP BY status HAVING COUNT(*) > 2;' },
        ],
        correctOptionId: 'a',
      }),
      {
        id: 'l3-p3', kind: 'complete', skill: 'aggregate',
        title: 'Units by product',
        prompt: 'Complete the query to add quantities for each product ID.',
        hint: 'Group by the non-aggregate column product_id.',
        explanation: 'SUM(quantity) adds the item quantities within each product group.',
        solutionSql: 'SELECT product_id, SUM(quantity) AS units_sold FROM order_items GROUP BY product_id;',
        templateParts: ['SELECT product_id, SUM(quantity) AS units_sold FROM order_items ', ';'],
        blankLabels: ['grouping clause'],
        blankAnswers: ['GROUP BY product_id'],
      },
      {
        id: 'l3-p4', kind: 'fix', skill: 'aggregate',
        title: 'One count per category',
        prompt: 'Fix the query to show each product category and its product_count.',
        hint: 'Add a GROUP BY for category.',
        explanation: 'A category beside COUNT(*) needs a matching GROUP BY.',
        starterSql: 'SELECT category, COUNT(*) AS product_count FROM products;',
        solutionSql: 'SELECT category, COUNT(*) AS product_count FROM products GROUP BY category;',
      },
      {
        id: 'l3-p5', kind: 'write', skill: 'aggregate',
        title: 'Average category price',
        prompt: 'Show each product category and its average price, named avg_price.',
        hint: 'Use AVG(price) and GROUP BY category.',
        explanation: 'AVG(price) calculates one average inside each category group.',
        solutionSql: 'SELECT category, AVG(price) AS avg_price FROM products GROUP BY category;',
      },
      choose({
        id: 'l3-p6', skill: 'aggregate', title: 'Repeat customers',
        prompt: 'Which query shows customer IDs with more than one order and their order_count?',
        hint: 'Use HAVING COUNT(*) > 1 after grouping by customer_id.',
        explanation: 'HAVING keeps only groups whose count is greater than one.',
        options: [
          { id: 'a', sql: 'SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id HAVING COUNT(*) = 1;' },
          { id: 'b', sql: 'SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id HAVING COUNT(*) > 2;' },
          { id: 'c', sql: 'SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id HAVING COUNT(*) >= 1;' },
          { id: 'd', sql: 'SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id HAVING COUNT(*) > 1;' },
        ],
        correctOptionId: 'd',
      }),
      {
        id: 'l3-p7', kind: 'match', skill: 'aggregate',
        title: 'Recreate the status summary',
        prompt: 'Write a query that produces the target result table.',
        hint: 'Group orders by status, count each group, then keep groups with more than two orders.',
        explanation: 'Grouping builds the counts; HAVING keeps the larger groups.',
        solutionSql: 'SELECT status, COUNT(*) AS order_count FROM orders GROUP BY status HAVING COUNT(*) > 2;',
      },
      {
        id: 'l3-p8', kind: 'write', skill: 'aggregate', difficulty: 'boss',
        title: 'Repeat shipped buyers',
        prompt: 'Show customer IDs and shipped-order counts for customers who have at least two shipped orders.',
        hint: 'Keep shipped orders before counting each customer’s rows.',
        explanation: 'Filter individual orders, group by buyer, then keep groups of two or more.',
        solutionSql: "SELECT customer_id, COUNT(*) AS shipped_count FROM orders WHERE status = 'shipped' GROUP BY customer_id HAVING COUNT(*) >= 2;",
      },
      {
        id: 'l3-p9', kind: 'order', skill: 'aggregate',
        title: 'Group and filter clause order',
        prompt: 'Assemble the clauses in the correct order to find customer IDs with multiple orders and their order_count, sorted from highest customer ID to lowest.',
        hint: 'Syntactic sequence: SELECT -> FROM -> GROUP BY -> HAVING -> ORDER BY.',
        explanation: 'In SQL, GROUP BY precedes HAVING, which in turn precedes ORDER BY.',
        clauses: [
          'SELECT customer_id, COUNT(*) AS order_count',
          'FROM orders',
          'GROUP BY customer_id',
          'HAVING COUNT(*) > 1',
          'ORDER BY customer_id DESC;',
        ],
        solutionSql: "SELECT customer_id, COUNT(*) AS order_count\nFROM orders\nGROUP BY customer_id\nHAVING COUNT(*) > 1\nORDER BY customer_id DESC;",
        orderMatters: true,
      },
    ],
    exam: [
      {
        id: 'l3-e1', kind: 'write', skill: 'aggregate',
        title: 'Units in each order',
        prompt: 'Show each order_id and the sum of its item quantities, named total_units.',
        hint: 'Group order_items by order_id and SUM(quantity).',
        explanation: 'Each order group gets its own total quantity.',
        solutionSql: 'SELECT order_id, SUM(quantity) AS total_units FROM order_items GROUP BY order_id;',
      },
      {
        id: 'l3-e2', kind: 'complete', skill: 'aggregate',
        title: 'Products per category',
        prompt: 'Fill in the group column to count products in each category.',
        hint: 'Group by the category shown in SELECT.',
        explanation: 'GROUP BY category matches the non-aggregate selected column.',
        solutionSql: 'SELECT category, COUNT(*) AS product_count FROM products GROUP BY category;',
        templateParts: ['SELECT category, COUNT(*) AS product_count FROM products GROUP BY ', ';'],
        blankLabels: ['group column'],
        blankAnswers: ['category'],
      },
      {
        id: 'l3-e3', kind: 'fix', skill: 'aggregate',
        title: 'Common statuses',
        prompt: 'Fix the query to show statuses with more than one order and their order_count.',
        hint: 'The HAVING comparison should be greater than one.',
        explanation: 'HAVING COUNT(*) > 1 keeps repeated statuses.',
        starterSql: 'SELECT status, COUNT(*) AS order_count FROM orders GROUP BY status HAVING COUNT(*) = 1;',
        solutionSql: 'SELECT status, COUNT(*) AS order_count FROM orders GROUP BY status HAVING COUNT(*) > 1;',
      },
      choose({
        id: 'l3-e4', skill: 'aggregate', title: 'Shipped order count',
        prompt: 'Which query returns the number of shipped orders as shipped_count?',
        hint: 'Count only rows with shipped status.',
        explanation: 'WHERE filters before COUNT aggregates.',
        options: [
          { id: 'a', sql: "SELECT COUNT(*) AS shipped_count FROM orders WHERE status = 'pending';" },
          { id: 'b', sql: "SELECT COUNT(*) AS shipped_count FROM orders WHERE status = 'shipped';" },
          { id: 'c', sql: 'SELECT COUNT(*) AS shipped_count FROM orders;' },
          { id: 'd', sql: "SELECT COUNT(*) AS shipped_count FROM orders WHERE status = 'cancelled';" },
        ],
        correctOptionId: 'b',
      }),
      {
        id: 'l3-e5', kind: 'write', skill: 'aggregate',
        title: 'Lowest product price',
        prompt: 'Return the lowest product price as cheapest_price.',
        hint: 'MIN finds the smallest price.',
        explanation: 'MIN(price) finds the cheapest price in products.',
        solutionSql: 'SELECT MIN(price) AS cheapest_price FROM products;',
      },
      {
        id: 'l3-e6', kind: 'complete', skill: 'aggregate',
        title: 'Top price per category',
        prompt: 'Fill in the aggregate to show the highest price in each category.',
        hint: 'MAX finds the largest value.',
        explanation: 'MAX(price) compares prices within each category group.',
        solutionSql: 'SELECT category, MAX(price) AS top_price FROM products GROUP BY category;',
        templateParts: ['SELECT category, ', '(price) AS top_price FROM products GROUP BY category;'],
        blankLabels: ['aggregate'],
        blankAnswers: ['MAX'],
      },
      {
        id: 'l3-e7', kind: 'fix', skill: 'aggregate',
        title: 'Units, not lines',
        prompt: 'Fix the query so it returns total units ordered as total_units.',
        hint: 'Quantity records units on each line.',
        explanation: 'SUM(quantity) adds units; COUNT(*) counts item rows.',
        starterSql: 'SELECT COUNT(*) AS total_units FROM order_items;',
        solutionSql: 'SELECT SUM(quantity) AS total_units FROM order_items;',
      },
      choose({
        id: 'l3-e8', skill: 'aggregate', title: 'Orders by customer',
        prompt: 'Which query shows every customer_id that appears in orders and its order_count?',
        hint: 'Group orders by customer_id.',
        explanation: 'Grouping by the ID creates one total per customer.',
        options: [
          { id: 'a', sql: 'SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id;' },
          { id: 'b', sql: 'SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id HAVING COUNT(*) > 1;' },
          { id: 'c', sql: 'SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id HAVING COUNT(*) = 1;' },
          { id: 'd', sql: 'SELECT status, COUNT(*) AS order_count FROM orders GROUP BY status;' },
        ],
        correctOptionId: 'a',
      }),
    ],
    examDrawCount: 4,
    passCount: 3,
  },
  {
    id: 'join',
    number: 4,
    title: 'Connect the shop',
    subtitle: 'Combine related tables to answer bigger questions.',
    skills: ['join'],
    rules: [
      {
        title: 'Match related keys',
        body: 'JOIN connects rows from two tables. ON states the match: a foreign key equals its matching primary key.',
        example: 'SELECT o.id, c.name FROM orders AS o JOIN customers AS c ON o.customer_id = c.id;',
      },
      {
        title: 'Use short table names',
        body: 'Aliases such as o and c make it clear which table owns each column.',
        example: 'SELECT o.id AS order_id, c.name AS customer_name FROM orders AS o JOIN customers AS c ON o.customer_id = c.id;',
      },
      {
        title: 'Keep using earlier skills',
        body: 'A joined result can still use WHERE, GROUP BY, and ORDER BY.',
        example: "SELECT c.name FROM orders AS o JOIN customers AS c ON o.customer_id = c.id WHERE o.status = 'shipped';",
      },
    ],
    exercises: [
      {
        id: 'l4-p1', kind: 'write', skill: 'join',
        title: 'Who placed each order?',
        prompt: 'Show every order ID as order_id and its customer name as customer_name.',
        hint: 'Join orders.customer_id to customers.id.',
        explanation: 'The foreign key customer_id identifies the matching customer row.',
        solutionSql: 'SELECT o.id AS order_id, c.name AS customer_name FROM orders AS o JOIN customers AS c ON o.customer_id = c.id;',
      },
      choose({
        id: 'l4-p2', skill: 'join', title: 'Products in order items',
        prompt: 'Which query shows the product_name and quantity for every order item?',
        hint: 'Join order_items.product_id to products.id.',
        explanation: 'The order item stores the product key and quantity; products stores the name.',
        options: [
          { id: 'a', sql: 'SELECT p.name AS product_name, oi.quantity FROM order_items AS oi JOIN products AS p ON oi.order_id = p.id;' },
          { id: 'b', sql: 'SELECT p.name AS product_name, oi.quantity FROM order_items AS oi JOIN products AS p ON oi.product_id = p.id;' },
          { id: 'c', sql: 'SELECT p.name AS product_name, oi.quantity FROM order_items AS oi JOIN products AS p ON oi.product_id = p.id WHERE oi.quantity > 1;' },
          { id: 'd', sql: 'SELECT p.name AS product_name FROM order_items AS oi JOIN products AS p ON oi.product_id = p.id;' },
        ],
        correctOptionId: 'b',
      }),
      {
        id: 'l4-p3', kind: 'complete', skill: 'join',
        title: 'Shipped order owners',
        prompt: 'Fill in the join condition to show shipped order IDs and customer names.',
        hint: 'Match o.customer_id with c.id.',
        explanation: 'The ON condition links each order to its actual customer.',
        solutionSql: "SELECT o.id AS order_id, c.name AS customer_name FROM orders AS o JOIN customers AS c ON o.customer_id = c.id WHERE o.status = 'shipped';",
        templateParts: [
          'SELECT o.id AS order_id, c.name AS customer_name FROM orders AS o JOIN customers AS c ON ',
          " WHERE o.status = 'shipped';",
        ],
        blankLabels: ['join condition'],
        blankAnswers: ['o.customer_id = c.id'],
      },
      {
        id: 'l4-p4', kind: 'fix', skill: 'join',
        title: 'Match customers correctly',
        prompt: 'Fix the join so every order is paired with the customer who placed it.',
        hint: 'Order ID is different from customer ID.',
        explanation: 'Use orders.customer_id, not orders.id, to find the customer.',
        starterSql: 'SELECT o.id AS order_id, c.name AS customer_name FROM orders AS o JOIN customers AS c ON o.id = c.id;',
        solutionSql: 'SELECT o.id AS order_id, c.name AS customer_name FROM orders AS o JOIN customers AS c ON o.customer_id = c.id;',
        commonMistakes: [{
          sql: 'SELECT o.id AS order_id, c.name AS customer_name FROM orders AS o JOIN customers AS c ON o.id = c.id;',
          feedback: 'Order IDs and customer IDs are different keys. Connect o.customer_id to c.id.',
        }],
      },
      {
        id: 'l4-p5', kind: 'write', skill: 'join',
        title: 'Units sold by product',
        prompt: 'Show each sold product name as product_name and total item quantity as units_sold.',
        hint: 'Join order_items to products, then group by product ID and name.',
        explanation: 'The join adds names; SUM(quantity) totals each product’s item rows.',
        solutionSql: 'SELECT p.name AS product_name, SUM(oi.quantity) AS units_sold FROM order_items AS oi JOIN products AS p ON oi.product_id = p.id GROUP BY p.id, p.name;',
        requiredPatterns: [{ pattern: '\\bJOIN\\b', label: 'a JOIN' }],
      },
      choose({
        id: 'l4-p6', skill: 'join', title: 'Shipped timeline',
        prompt: 'Which query shows customer names and shipped order dates, earliest first?',
        hint: 'Join the right keys, filter shipped, then sort date ASC.',
        explanation: 'The join identifies customers; WHERE and ORDER BY shape the timeline.',
        options: [
          { id: 'a', sql: "SELECT c.name AS customer_name, o.order_date FROM orders AS o JOIN customers AS c ON o.customer_id = c.id WHERE o.status = 'shipped' ORDER BY o.order_date DESC;" },
          { id: 'b', sql: "SELECT c.name AS customer_name, o.order_date FROM orders AS o JOIN customers AS c ON o.customer_id = c.id WHERE o.status = 'pending' ORDER BY o.order_date ASC;" },
          { id: 'c', sql: "SELECT c.name AS customer_name, o.order_date FROM orders AS o JOIN customers AS c ON o.id = c.id WHERE o.status = 'shipped' ORDER BY o.order_date ASC;" },
          { id: 'd', sql: "SELECT c.name AS customer_name, o.order_date FROM orders AS o JOIN customers AS c ON o.customer_id = c.id WHERE o.status = 'shipped' ORDER BY o.order_date ASC;" },
        ],
        correctOptionId: 'd', orderMatters: true,
      }),
      {
        id: 'l4-p7', kind: 'bug', skill: 'join',
        title: 'Wrong customer on the report',
        prompt: 'The report runs, but some orders show the wrong customer. Fix its logic.',
        hint: 'The customer key is stored on each order.',
        explanation: 'The join must connect orders.customer_id with customers.id.',
        starterSql: 'SELECT o.id AS order_id, c.name AS customer_name FROM orders o JOIN customers c ON o.id = c.id;',
        solutionSql: 'SELECT o.id AS order_id, c.name AS customer_name FROM orders o JOIN customers c ON o.customer_id = c.id;',
        commonMistakes: [{
          sql: 'SELECT o.id AS order_id, c.name AS customer_name FROM orders o JOIN customers c ON o.id = c.id;',
          feedback: 'Order IDs identify orders, not their owners. Use o.customer_id to find the customer.',
        }],
      },
      {
        id: 'l4-p8', kind: 'write', skill: 'join', difficulty: 'boss',
        title: 'Thank loyal shipped buyers',
        prompt: 'Show IDs, names, and shipped-order counts for customers with at least two shipped orders.',
        hint: 'Connect orders to customers before counting each buyer’s shipped orders.',
        explanation: 'The customer link adds names to the grouped shipment counts.',
        solutionSql: "SELECT c.id, c.name, COUNT(o.id) AS shipped_orders FROM customers c JOIN orders o ON o.customer_id = c.id WHERE o.status = 'shipped' GROUP BY c.id, c.name HAVING COUNT(o.id) >= 2;",
      },
      {
        id: 'l4-p9', kind: 'explain', skill: 'join',
        title: 'Decipher the join query',
        prompt: 'Study the query below. Which plain-English description accurately explains what it produces?',
        hint: 'Look at the table being joined, the WHERE filter, and the aggregate.',
        explanation: 'The query joins customers to orders, filters for pending status, and counts how many pending orders each customer has.',
        starterSql: "SELECT c.name, COUNT(o.id) AS pending_count\nFROM customers c\nJOIN orders o ON o.customer_id = c.id\nWHERE o.status = 'pending'\nGROUP BY c.id, c.name;",
        solutionSql: "SELECT c.name, COUNT(o.id) AS pending_count\nFROM customers c\nJOIN orders o ON o.customer_id = c.id\nWHERE o.status = 'pending'\nGROUP BY c.id, c.name;",
        answerOptions: [
          { id: 'a', label: 'Counts how many pending orders each customer currently has.' },
          { id: 'b', label: 'Lists all customers and the total monetary value of their pending items.' },
          { id: 'c', label: 'Finds orders that have been waiting without a customer assigned.' },
          { id: 'd', label: 'Returns customers whose shipped orders outnumber their pending orders.' },
        ],
        correctAnswerId: 'a',
      },
    ],
    exam: [
      {
        id: 'l4-e1', kind: 'write', skill: 'join',
        title: 'Multi-unit items',
        prompt: 'Show order_id, product_name, and quantity for order items with quantity at least 2.',
        hint: 'Join product_id to products.id and filter quantity >= 2.',
        explanation: 'A joined product name can be filtered by quantity from order_items.',
        solutionSql: 'SELECT oi.order_id, p.name AS product_name, oi.quantity FROM order_items AS oi JOIN products AS p ON oi.product_id = p.id WHERE oi.quantity >= 2;',
      },
      {
        id: 'l4-e2', kind: 'complete', skill: 'join',
        title: 'Order customer pairs',
        prompt: 'Fill in the join condition to show each customer_name and order_id.',
        hint: 'Match c.id to o.customer_id.',
        explanation: 'Customer IDs are stored as a foreign key on orders.',
        solutionSql: 'SELECT c.name AS customer_name, o.id AS order_id FROM customers AS c JOIN orders AS o ON c.id = o.customer_id;',
        templateParts: [
          'SELECT c.name AS customer_name, o.id AS order_id FROM customers AS c JOIN orders AS o ON ',
          ';',
        ],
        blankLabels: ['join condition'],
        blankAnswers: ['c.id = o.customer_id'],
      },
      {
        id: 'l4-e3', kind: 'fix', skill: 'join',
        title: 'Orders per customer',
        prompt: 'Fix the join to show each customer with orders and their order_count.',
        hint: 'Join customer ID to the customer_id stored on orders.',
        explanation: 'The grouping is correct; the ON condition must use o.customer_id.',
        starterSql: 'SELECT c.name AS customer_name, COUNT(o.id) AS order_count FROM customers AS c JOIN orders AS o ON c.id = o.id GROUP BY c.id, c.name;',
        solutionSql: 'SELECT c.name AS customer_name, COUNT(o.id) AS order_count FROM customers AS c JOIN orders AS o ON c.id = o.customer_id GROUP BY c.id, c.name;',
      },
      choose({
        id: 'l4-e4', skill: 'join', title: 'Order item names',
        prompt: 'Which query shows each order item ID and its product name?',
        hint: 'Match order_items.product_id to products.id.',
        explanation: 'The product key on each item identifies the matching product.',
        options: [
          { id: 'a', sql: 'SELECT oi.id AS item_id, p.name AS product_name FROM order_items AS oi JOIN products AS p ON oi.order_id = p.id;' },
          { id: 'b', sql: 'SELECT oi.id AS item_id, p.name AS product_name FROM order_items AS oi JOIN products AS p ON oi.product_id = p.id;' },
          { id: 'c', sql: 'SELECT oi.id AS item_id, p.name AS product_name FROM order_items AS oi JOIN products AS p ON oi.product_id = p.id WHERE oi.quantity > 1;' },
          { id: 'd', sql: 'SELECT oi.id AS item_id, p.category AS product_name FROM order_items AS oi JOIN products AS p ON oi.product_id = p.id;' },
        ],
        correctOptionId: 'b',
      }),
      {
        id: 'l4-e5', kind: 'write', skill: 'join',
        title: 'Customer cities for orders',
        prompt: 'Show every order ID as order_id and its customer city as customer_city.',
        hint: 'The order has customer_id; the customer has city.',
        explanation: 'Joining through customer_id makes the city available.',
        solutionSql: 'SELECT o.id AS order_id, c.city AS customer_city FROM orders AS o JOIN customers AS c ON o.customer_id = c.id;',
      },
      {
        id: 'l4-e6', kind: 'complete', skill: 'join',
        title: 'Product categories on items',
        prompt: 'Fill in the join condition to show each item ID and its product category.',
        hint: 'Match the product key on each item to products.id.',
        explanation: 'The ON clause links an item to its product row.',
        solutionSql: 'SELECT oi.id AS item_id, p.category FROM order_items AS oi JOIN products AS p ON oi.product_id = p.id;',
        templateParts: ['SELECT oi.id AS item_id, p.category FROM order_items AS oi JOIN products AS p ON ', ';'],
        blankLabels: ['join condition'],
        blankAnswers: ['oi.product_id = p.id'],
      },
      {
        id: 'l4-e7', kind: 'fix', skill: 'join',
        title: 'Customer for each shipped order',
        prompt: 'Fix the join to show each shipped order ID and its customer name.',
        hint: 'An order refers to its customer with customer_id.',
        explanation: 'Match o.customer_id with c.id to identify the actual customer.',
        starterSql: "SELECT o.id AS order_id, c.name AS customer_name FROM orders AS o JOIN customers AS c ON o.id = c.id WHERE o.status = 'shipped';",
        solutionSql: "SELECT o.id AS order_id, c.name AS customer_name FROM orders AS o JOIN customers AS c ON o.customer_id = c.id WHERE o.status = 'shipped';",
      },
      choose({
        id: 'l4-e8', skill: 'join', title: 'Units by product',
        prompt: 'Which query returns each sold product name and its units_sold?',
        hint: 'Join products to items and add quantities by product.',
        explanation: 'SUM(quantity) totals all item rows for each product.',
        options: [
          { id: 'a', sql: 'SELECT p.name AS product_name, COUNT(*) AS units_sold FROM order_items AS oi JOIN products AS p ON oi.product_id = p.id GROUP BY p.id, p.name;' },
          { id: 'b', sql: 'SELECT p.name AS product_name, SUM(oi.quantity) AS units_sold FROM order_items AS oi JOIN products AS p ON oi.order_id = p.id GROUP BY p.id, p.name;' },
          { id: 'c', sql: 'SELECT p.name AS product_name, SUM(oi.quantity) AS units_sold FROM order_items AS oi JOIN products AS p ON oi.product_id = p.id GROUP BY p.id, p.name;' },
          { id: 'd', sql: 'SELECT p.category AS product_name, SUM(oi.quantity) AS units_sold FROM order_items AS oi JOIN products AS p ON oi.product_id = p.id GROUP BY p.category;' },
        ],
        correctOptionId: 'c',
      }),
    ],
    examDrawCount: 4,
    passCount: 3,
  },
];
